### ISSUE TITLE
Animate.css does not seem to work with Laravel 7.10.3

### ISSUE THREAD

**Issue by techtag** [animate-css/animate.css#1055]
I am trying to use Animate.css on my Laravel project. I installed Animate.css using following command:
`$ npm install animate.css --save`
and included it in \resources\sass\app.scss file
`@import "~animate.css/animate.css";`
and I ran following npm command
`npm run dev`
When I look in to View Page Source on the browser, animate.css seem to be included but HTML elements are not animated. Animation seem to be working in Edge but not in Chrome (v81.0.4044.138)  or FF (v76.0).
Can someone help me get this working? 
Thank you in advance

**Comment by eltonmesquita** [comment]
Please, read the [migration guide](https://animate.style/#migration).
