### ISSUE TITLE
Horizontal scroll bar issue with fadeOutRight

### ISSUE THREAD

**Issue by lushushu137** [animate-css/animate.css#1059]
When the item size is too big and fadeOutRight was added, it doesn't disappear. Instead, it stretches the horizontal scroll bar and leaves big blank space on the right side.  However, fadeOutLeft has no such problem.

The code is as follows:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js">
	</script>
	<style>
		#container {
			width: 1000px;
			height: 1000px;
			border: solid 1px;
			position: relative;
			margin: 0px auto;
		}

		#left {
			width: 1000px;
			height: 1000px;
			background-color: pink;
			position: absolute;
			top: 10px;
		}

		#right {
			width: 1000px;
			height: 1000px;
			background-color: lightblue;
			position: absolute;
			right: 10px;
		}
	</style>
	<script>
		$(document).ready(function () {
			$("button").click(function () {
				$("#left").addClass("animate__animated animate__fadeOutLeftBig");
				$("#right").addClass("animate__animated animate__fadeOutRightBig");
			});
		});
	</script>
</head>

<body>
	<button>click me!</button>
	<div id="container">
		<div id="left"></div>
		<div id="right"></div>
	</div>

</body>

</html>
```

**To Reproduce** Steps to reproduce the behavior:

1. Open in browser
2. Click the button

screenshot before click:
![before](https://user-images.githubusercontent.com/60133071/81578450-6896f300-93dd-11ea-9513-34bed9d898a2.jpeg)

screenshot after click:
![after](https://user-images.githubusercontent.com/60133071/81578455-6a60b680-93dd-11ea-9c4a-5cb9a5238f0e.png)

**Desktop (please complete the following information):**

- OS: MAC OS 10.13.6
- Browser Chrome 81.0.4044.138

**Comment by eltonmesquita** [comment]
Please, see then Overflow section on our [documentation](https://animate.style/#best)
