### ISSUE TITLE
[Feature Request] I think we need old version documentation

### ISSUE THREAD

**Issue by rizkiandrianto** [animate-css/animate.css#1062]
**Is your feature request related to a problem? Please describe.** Yes, really hard to find friendly old class documentation.

**Describe the solution you'd like** We need old documentation page, that we can copy paste v3 css class.

**Describe alternatives you've considered** At least we had old README.

**Additional context** old https://daneden.github.io/animate.css/.

**Comment by eltonmesquita** [comment]
Hi @rizkiandrianto, sorry, but the need for the old docs? The new one is based on the last on with a few more additions. The usage, besides the class prefix, is basically the same. There's also the complete list of animations in the first part of the demo-site.

I honestly can't see why to keep both versions. But I'll keep this open to hear more about the request.

**Comment by 3epnm** [comment]
I have to agree with @rizkiandrianto. I use animate.css in version 3.0 - and it has changed a bit - however small this change may be. In itself, it is good practice to document the legacy versions of an excellent product. At least I don't feel any pain for an update.

**Comment by eltonmesquita** [comment]
It's added to the readme now. I think there's no need to add this to the website as there never was any docs in the website.

**Comment by PeterPan73** [comment]
[http://web.archive.org/web/20191129075511/https://daneden.github.io/animate.css/](addressl)
