### ISSUE TITLE
Add favicon and graph metatags to website

### ISSUE THREAD

**Issue by eltonmesquita** [animate-css/animate.css#1066]
We need to add the final touches to website:

- [x] Add Favicons
- [x] Add graph meta tags for sharing

**Comment by WarenGonzaga** [comment]
Thanks @eltonmesquita for assigning the task... will work on it.

**Comment by WarenGonzaga** [comment]
@eltonmesquita oh I almost forgot this task... I'm going to continue this one...

**Comment by WarenGonzaga** [comment]
Hi @eltonmesquita this task is done... PR sent...

**Comment by WarenGonzaga** [comment]
@eltonmesquita you can now close this one.

**Comment by WarenGonzaga** [comment]
This is the preview of this changes.

![image](https://user-images.githubusercontent.com/15052701/92382611-710afa80-f13f-11ea-972c-6e1cc619718a.png)

Hope you like it!

**Comment by eltonmesquita** [comment]
Yeah, that's cool! I just published the new version and it's live ;D

**Comment by WarenGonzaga** [comment]
@eltonmesquita I will PR a new changes for the open graph I kind of having issues with open graph due to the usage of path instead of URL of actual file.
