### ISSUE TITLE
Broken link on Animate.css

### ISSUE THREAD

**Issue by a-developer-and-her-mac** [animate-css/animate.css#1067]
On Animate.css, in the basic usage section, if you click on the link to Best Practices, it won't take you anywhere. 
<img width="1440" alt="Screen Shot 2020-05-29 at 7 39 41 AM" src="https://user-images.githubusercontent.com/64797765/83272327-dd10b680-a17f-11ea-82b2-2f5c9fb014e9.png">

**Comment by eltonmesquita** [comment]
Nice catch! That's a bug in the compile script. I'll fix this soon.
