### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by parkdonggyu** [animate-css/animate.css#1068]
I'm so glad I found your project. it is very helpful to who study css like me. 

![commit 3](https://user-images.githubusercontent.com/62459582/83961243-2ffb1400-a8cc-11ea-9cd5-97e7f7604d67.PNG)
![commit 3-1](https://user-images.githubusercontent.com/62459582/83961244-3093aa80-a8cc-11ea-8141-69fafa46a314.PNG)

both links cannot found could you chceck it?

**Comment by eltonmesquita** [comment]
Thanks for noticing that! I've fixed this on #1069
