### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by daneden** [animate-css/animate.css#1070]
From IETF’s [“Terminology, Power, and Oppressive Language”](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1): 

> Master-slave is an oppressive metaphor that will and should never become fully detached from history. Aside from being unprofessional and oppressive it stifles participation […]

From a technical POV, it takes less that 3 minutes to change the branch name via GitHub’s UI. Just wanted to open an issue to make sure I’m not missing any other places we’d need to explicitly make this name change.

**Comment by daneden** [comment]
Looks like there are a [handful of docs references](https://github.com/animate-css/animate.css/search?q=master&unscoped_q=master) that need updating at least

**Comment by eltonmesquita** [comment]
Nice! Will we have to move the github pages back to the `gh-branch` again? That would break the current build system.

**Comment by eltonmesquita** [comment]
I just forked the repo to mess around with the settings and it seems that you can only use master and gh-pages to publish the website.

So, do we do this with github actions?

**Comment by WarenGonzaga** [comment]
> I just forked the repo to mess around with the settings and it seems that you can only use master and gh-pages to publish the website.
> 
> So, do we do this with github actions?

I guess, this is the right time to use github actions.

**Comment by eltonmesquita** [comment]
Do you have any experience with that @WarenGonzaga? Would you like to take the task?

**Comment by WarenGonzaga** [comment]
@eltonmesquita a little bit experience... I can try, just give me exact instructions.

**Comment by eltonmesquita** [comment]
Cool @WarenGonzaga .
Basically, you need to configure an action to publish the docs (the `docs` folder) automatically to the `gh-page` branch. The action should compile things on the <del>master</del> <in>main</in> branch and copy/commit/publish the files to the `gh-page` branch.

I've got no experience on actions, but I can try to help if you need.

**Comment by ColdTuna** [comment]
Oh god 🤦

**Comment by daneden** [comment]
@eltonmesquita @WarenGonzaga looks like GitHub now allows [building pages from any branch](https://github.blog/changelog/2020-07-31-build-and-deploy-github-pages-from-any-branch-beta/) 😄 I’ll create the `main` branch and confirm it works as expected.

**Comment by daneden** [comment]
Pages are working; going to tentatively update the default branch to use `main`. If we don't see any issues after a week or so, we can probably safely delete the `master` branch :)

**Comment by eltonmesquita** [comment]
Great news @daneden !
