### ISSUE TITLE
Custom Builds not Working

### ISSUE THREAD

**Issue by lbassuncao** [animate-css/animate.css#1073]
I'm using Parcel module bundler, after the instructions on https://animate.style/#custom-builds, I noticed that the compilation does not include some classes and there's nowhere to find them on project folder. The missing classes after compilation are:

![Missing](https://user-images.githubusercontent.com/8853276/84651571-1aa46c00-af02-11ea-98ec-a9a7a32e91c2.png)

**Comment by eltonmesquita** [comment]
Hi, sorry but I didn't get it right. How are you building it? Are you using parcel? The repository doesn't use parcel at all, so you probably have issues related to that. The instructions are for cloning the repository and using our building scripts.

**Comment by lbassuncao** [comment]
Hi. And thanks for your quick answer. It's my mistake because when compiled with Parcel, the bundler ignores the prefix "_animate". It's compiling just fine, I just had to ignore the prefixes stated on official website. For instance, instead of using: 

`<h1 class="animate__animated animate__bounce">An animated element</h1>`

I have to use:

`<h1 class="animated bounce">An animated element</h1>`

Because the bundler doesn't insert the prefix "animate__".

Thanks.

**Comment by AlonsoK28** [comment]
> Hi. And thanks for your quick answer.
> 
> It's was my mistake because when compiled with Parcel, the bundler ignores the prefix "`animate__`". It's compiling just fine, I just had to ignore the prefixes stated on official website. For instance, instead of using:
> 
> `<h1 class="animate__animated animate__bounce">An animated element</h1>`
> 
> I have to use:
> 
> `<h1 class="animated bounce">An animated element</h1>`
> 
> Because the bundler doesn't insert the prefix "animate__".
> 
> Thanks.

Thanks, I think that an escenario like this sholud be documented in official docs

**Comment by eltonmesquita** [comment]
I updated the docs on #1451 to warn about this scenario.
