### ISSUE TITLE
Usage with Javascript: function call

### ISSUE THREAD

**Issue by xadim** [animate-css/animate.css#1075]
When you call the function as shown in the example with the class name `animate__bounce ` it won't work because the prefix adds an extra `animate__`. Unless the prefix is removed, calls should be like animateCSS('.my-element', 'bounce');
Hope my explanations are clear enough for you to replicate the bug.

Thank you for this beautiful library!!

**Comment by eltonmesquita** [comment]
Hi, you're completely right. Sorry for that.

I've already fixed it. It should be updated soon.
