### ISSUE TITLE
Js library for better control over animation

### ISSUE THREAD

**Issue by sparkingdark** [animate-css/animate.css#1076]
# My idea 
I suggest some basic utility functions in JavaScript to create elements,control,modify the elements in the website.You put some code in the website like need to code everytime to make the elements animated using js . Instead of that I suggest a library by which we can just import that and use these utility function.I give a link of my pen:
https://codepen.io/debomastet335/pen/pogeNeY

**Comment by eltonmesquita** [comment]
Thanks for the suggestion. That's something we've been talking internally about lately. Let's see how it turns out.

**Comment by sparkingdark** [comment]
That's awesome if possible can I try to work?

**Comment by eltonmesquita** [comment]
We're still working internally on this. As soon as we get the first public release, you're more than welcome to contribute!

In the meantime, feel free to suggest what you think would be important to include in the library.

**Comment by WarenGonzaga** [comment]
Hi @sparkingdark awesome idea, however this idea is on our pipeline internally and I guess we have a better approach for this. Give us more time to work on it and release the first version with this implementation we are looking forward for this new feature for the future version of animate.css

**Comment by koffiisen** [comment]
> # My idea
> I suggest some basic utility functions in JavaScript to create elements,control,modify the elements in the website.You put some code in the website like need to code everytime to make the elements animated using js . Instead of that I suggest a library by which we can just import that and use these utility function.I give a link of my pen:
> https://codepen.io/debomastet335/pen/pogeNeY

Hi, check here [https://github.com/koffiisen/Animate.js](https://github.com/koffiisen/Animate.js)

**Comment by koffiisen** [comment]
Hi everybody,

I created a javascript version 4 months ago  [Animate.js](https://github.com/koffiisen/Animate.js) . Watch and give your opinion. Could you integrate my javascript version? Ideas for improvement are welcome.

https://github.com/koffiisen/Animate.js

Thank.

**Comment by WarenGonzaga** [comment]
Hi @koffiisen, nice work... however I checked your project and this is away from our original plan on our pipeline. We don't think that we can use your library to integrate in animate.css since your library does the job of our CSS library. So the user can either use your JS library or CSS library that we created... what do you think @eltonmesquita and @daneden?

**Comment by eltonmesquita** [comment]
I'm with @WarenGonzaga on this. We have something in the works that goes in a whole different direction.

I'll also close this as, in the end, belongs to another library.
