### ISSUE TITLE
yarn add animate.css doesn't work

### ISSUE THREAD

**Issue by Draichi** [animate-css/animate.css#1077]
Hey, i found a lilte bug,
When running `yarn add animate.css` the package is not imported (at least on dev mode)

The work around is: import it using cdn

Just wanna post it so anyone who face the same issue can see

thanks

**Comment by alishaevn** [comment]
`npm install animate.css --save` doesn't work either.
I'm working on an app with gatsby.js though, so importing using the cdn isn't possible.

**Comment by daneden** [comment]
Hey @Draichi/@alishaevn! You should be able to include animate.css on your page by `require` or `import`ing it. For example, in Gatsby, you can import Animate.css in `gatsby-browser.js` to include it on every page, and then add the class names to elements:

```js
// In gatsby-browser.js
import "animate.css"
```

```jsx
// In src/pages/index.js
<h1 className="animate__animated animate__zoomInDown">Animated heading</h1>
```

Here’s a working example, set up by running `npx gatsby new animate-css-test` and inside the project `yarn add animate.css`: 

- [Live site](https://animate-css-test-1vzzer9ca.vercel.app/)
- [`gatsby-browser.js` source](https://vercel.com/daneden/animate-css-test/ffrx2lofv/source?f=src%2Fgatsby-browser.js)
- [`src/pages/index.js` source](https://vercel.com/daneden/animate-css-test/ffrx2lofv/source?f=src%2Fsrc%2Fpages%2Findex.js)

**Comment by unikitty37** [comment]
Would it be worth mentioning this in the docs? They do kind of imply that running `yarn add` or `npm install` will be all you need to do 🙂

**Comment by snolangps** [comment]
nextjs after adding `import 'animate.css'` still doesn't work :(

**Comment by hdehal** [comment]
@daneden Perhaps this was super obvious, but your example above took me much searching to find -- there are tons of related questions on how to simply import and get started with Animate.css on StackOverflow (with _wrong_ answers).

Wondering if we can add this to the existing documentation:

With yarn:

`$ yarn add animate.css`

```
import "animate.css"
<h1 className="animate__animated animate__zoomInDown">Animated heading</h1>
```

**Comment by eltonmesquita** [comment]
@hdehal , it makes sense. I would gladly accept a PR with the adjustments and, if possible,  an additional note pointing out that it also depends on your tools and their specific configurations, as any bundler/task-runner/whatever will need proper configurations so the imports will work,
