### ISSUE TITLE
animation runs before div is on the screen 

### ISSUE THREAD

**Issue by mfwebmaster** [animate-css/animate.css#1078]
good day 

I have a page that is scrolling down and have animations set up on a Section 

Below is the code 
```
<section id="who-are-we" class="">
<div id="page" class="container">
<div class="row align-items-center h-100">
<div class="col-md-2 vericaltext-header pt-5 pb-5 animate__animated animate__fadeInUp animate__slower">
Some text
</div>
<div class="col-md-10 animate__animated animate__fadeInRight animate__delay-3s animate__slower>
Some text
</div>
</div>
</div>
</section>
```

The problem is that the **animation runs on page load** so by the time you scroll to a division the animation has already ran. 

Is there a way do you have the animation Run Once the elements is on screen?

**Comment by eltonmesquita** [comment]
This isn't something you can achieve with CSS only. You can build your own solution using Javascript (the intersection observer can make things easy) or just use a library like [AOS](https://michalsnik.github.io/aos/).

I'm closing this as we can't help much about that around here.
