### ISSUE TITLE
Documentation for animate__infinite is missing

### ISSUE THREAD

**Issue by fulldecent** [animate-css/animate.css#1081]
The documentation alludes to a class for infinite repeat and it explains that you should not use it.

Please update docs to actually show how to use that feature.

I am using `animate__infinite` to represent a ringing phone on a dashboard. I think this case is acceptable. And the feature should be warned but not deprecated.

**Comment by daneden** [comment]
Seems like a good call; we should probably at least show _how_ to use those repeater classes for the few legitimate use cases that may exist.

**Comment by thraizz** [comment]
It is also worth noting that infinite animations not only require `animation-duration: [..]s` but also `animation-iteration-count: infinite` to work properly - should this be added to the docs?

**Comment by fulldecent** [comment]
I am successfully using with only `animate__animated animate__infinite animate__tada`
