### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [animate-css/animate.css#1083]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by eltonmesquita** [comment]
We don't use any analytics solution.

**Comment by resynth1943** [comment]
Ahh, I found this https://cdnjs.com/libraries/animate.css/
