### ISSUE TITLE
Is Animate-css 4.1 compatible with wow.js ?

### ISSUE THREAD

**Issue by carlo-13** [animate-css/animate.css#1084]
Is Animate-css 4.1 compatible with wow.js ?

Hi there.

I’ve been using Animate-css for a while now, I am planning to update to version 4, but I was wondering, is it still compatible with wow.js ?

Also is there an alternative method to trigger the animates on scroll ?

Thanks.

**Comment by eltonmesquita** [comment]
You should have no problems using any animate.css version with wow as long as you apply the right classes (see [docs](https://animate.style)).

A more modern alternative to wow is [AOS](https://michalsnik.github.io/aos/). It works fine with animate.css too.

**Comment by carlo-13** [comment]
> You should have no problems using any animate.css version with wow as long as you apply the right classes (see [docs](https://animate.style)).
> 
> A more modern alternative to wow is [AOS](https://michalsnik.github.io/aos/). It works fine with animate.css too.

Hi @eltonmesquita, thank you for your reply.
I think the latest version of AOS.js is not compatible with animate.css 4.1 . 

I've tried the method [here](https://github.com/michalsnik/aos#integrating-external-css-animation-library-eg-animatecss) ( I've updates the classes to version 4.1 ), but no luck there.
