### ISSUE TITLE
Animation-duration fallback values

### ISSUE THREAD

**Issue by LukeTOBrien** [animate-css/animate.css#1086]
## Description
When no duration is specified with the `--animation-duration`  then the animation does not perform.  
If I inspect my element I can see:  
`animation-duration: var(--animate-duration);`  
I think you should be using [fallback values <declaration-value>](https://developer.mozilla.org/en-US/docs/Web/CSS/var) so that is the user doesn't specify a duration then it will default:  
`animation-duration: var(--animate-duration, 5s);`  

**To Reproduce** Steps to reproduce the behaviour:

Follow the [basic usage steps](https://animate.style/) and don't set any `--animation-duration`

> This is important because you follow the basic usage steps, and that's it!.... Oh no it isn't you have to set CSS Custom Properties.

**Comment by LukeTOBrien** [comment]
Looking at your source I do see that in `_vars.css` you are setting the properties, but I am building a **Web Component** so the CSS would be inside the shadow root.  
Perhaps shadow roots do not have the `:root` selector?

```
:root {
  --animate-duration: 1s;
  --animate-delay: 1s;
  --animate-repeat: 1;
}
```

**Comment by eltonmesquita** [comment]
You're almost right. We don't provide a fallback for the custom properties but we do compile them and provide a fallback for older browsers, which ends up providing a fallback for when the custom properties are not declared. As long as you stick to the `animated` class it should work.

But if you think it would be useful to provide the fallback anyway, I'd happily accept a PR with this 😄

**Comment by eltonmesquita** [comment]
I'm closing this as it's stale.
