### ISSUE TITLE
CSS Image Hover Effects Issue

### ISSUE THREAD

**Issue by Marcporms** [animate-css/animate.css#1087]
Please need your help, the box is not lign with the first 2 boxes shown in the attached screenshot (after adding 2 pictures), it should be inline with 2 first boxes same as attached (original output). i just copy and paste the first code inside (<div class="box"> but the output shown different now. any advice?

Index

!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Css Image Hover Effects</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <div class="container">
            <div class="box">
                <div class="imgBox">
                    <img src="Image1.Jpg" alt="Image" height="300" width="300">
                </div>
                <div class="details">
                    <div class="content">
                        <h2>What is Lorem Ipsum?</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="imgBox">
                    <img src="Image2.jpg" alt="Image" height="300" width="300">
                </div>
                <div class="details">
                    <div class="content">
                        <h2>What is Lorem Ipsum?</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                    </div>
                </div>
            </div>
			<div class="container">
            <div class="box">
                <div class="imgBox">
                    <img src="Image3.jpg" alt="Image" height="300" width="300">
                </div>
                <div class="details">
                    <div class="content">
                        <h2>What is Lorem Ipsum?</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                    </div>
                </div>
            </div>
			<div class="container">
            <div class="box">
                <div class="imgBox">
                    <img src="Image4.jpg" alt="Image" height="300" width="300">
                </div>
                <div class="details">
                    <div class="content">
                        <h2>What is Lorem Ipsum?</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                    </div>
                </div>
            </div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
        </div>
    </body>
</html>

CSS

body
{
    margin: 0;
    padding: 0;
    background: #262626;
    font-family: sans-serif;
}
.container
{
    width: 1280px;   
    margin: 70px auto 0;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.container .box
{
    position: relative;
    width: 300px;
    height: 300px;   
    background: #ff0;
    margin: 10px;
    box-sizing: border-box;
    display: inline-block;   
}
.container .box .imgBox
{
    position: relative;  
    overflow: hidden;
}
.container .box .imgBox img
{
    max-width: 100%;    
    transition: transform 2s;
}
.container .box:hover .imgBox img
{
    transform: scale(1.2);
}
.container .box .details
{
    position: absolute;
    top: 10px;
    left: 10px;
    bottom: 10px;
    right: 10px;
    background: rgba(0,0,0,.8);
    transform: scaleY(0);
    transition: transform .5s;
}
.container .box:hover .details
{
    transform: scaleY(1);    
}
.container .box .details .content
{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    text-align: center;
    padding: 15px;
    color: #fff;
}
.container .box .details .content h2
{
    margin: 0;
    padding: 0;
    font-size: 20px;
    color: #ff0;
}
.container .box .details .content p
{
    margin: 10px 0 0;
    padding: 0;   
}
![Original output](https://user-images.githubusercontent.com/58650160/89200604-f2a7bf80-d5b8-11ea-9f3c-981dc3e9779d.jpg)
![Afte adding 2 pictures](https://user-images.githubusercontent.com/58650160/89200632-fafffa80-d5b8-11ea-9b22-a1d7a80e2484.jpg)

**Comment by eltonmesquita** [comment]
Hi @Marcporms. Sorry, but it'd be really hard to help without a reduced case. Even if that was the case, still it seems to be an issue related to CSS usage and you'll hardly get any help here, as this dedicated to problems and improvement of the library itself.

Mind that your problem must be related to the transform property being overwritten by animate. You can try to seek for help on Stackoverflow, you'll probably get much more help then around here.

Closing this as it's unrelated.
