### ISSUE TITLE
Postcss config files not added when using yarn add animate.css

### ISSUE THREAD

**Issue by thomasjulienalain** [animate-css/animate.css#1088]
Hello there !

I love the new animate.css <3 

I found out that the postCSS config file was not added using yarn add animate.css.

What I did :
- Run yarn add animate.css
- navbigate to path/to/animate.css/
- run npm install
- update source/animate.css
- run npm start in the root animate.css folder
- Got this error, and @import were not replaced in the resulted animate.css generated file : 
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

![image](https://user-images.githubusercontent.com/12446126/89310551-d81a2880-d642-11ea-87fd-62f2a3cc425f.png)

Then I grabbed it from the Github repo and i worked perfectely.

**Comment by eltonmesquita** [comment]
This is meant to work this way. We only provide the CSS files on `npm/yarn install`. If you need custom builds, you have to clone the repository.
