### ISSUE TITLE
Animate 4.1.0 + wow.js

### ISSUE THREAD

**Issue by MiniHarlock** [animate-css/animate.css#1091]
Hi there,

I’ve been using Animate.css for some years and it’s really cool. Thank you for this amazing job!

Today, as I landed on your page, I came to realize you had a brand new version going on, which is great news.

My concern is this viewport thing. I’ve always been using Animate + wow.js to trigger animations as elements were entering the viewport. I’m even surprised you didn’t include this option in your work, cause this is what everybody needs, right? Or is there something that I missed?

After some testings, I could find out the new animate version doesn’t work with wow.js. Unless I use the “compat” version, which you present as a temporary solution.

So my question is… Is there a simple way to trigger the animations when elements are in the viewport? What would you recommend?

Thanks!

**Comment by eltonmesquita** [comment]
Please see #1084. Animate.css will probably never provide this functionality as it's not possible to do this with CSS only. We might provide a js library to complement Animate.css but this future is not planned right now.

I'm closing this as it's not related to the library itself and has been answered before.
