### ISSUE TITLE
Option for initiating animation when div is in viewport.

### ISSUE THREAD

**Issue by Abhirup-99** [animate-css/animate.css#1098]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by eltonmesquita** [comment]
Please see #1091

**Comment by Abhirup-99** [comment]
@eltonmesquita can you update in the doc to add a js function to use animate.css with viewport. I can work on this. This would stop people from moving around searching for alternatives.

**Comment by eltonmesquita** [comment]
Hi @Abhirup-99. Sorry, but we've got no real plan for this right now. Maybe in the future, after solving #1076 we can do something about it.
