### ISSUE TITLE
New line "problem"

### ISSUE THREAD

**Issue by francogp** [animate-css/animate.css#1102]
**Describe the bug** A clear and concise description of what the bug is.
animate.css and animate.min.css start with
```

@charset "UTF-8";
```
and should not start with a new line. @charset should be the first line according to standards

**Comment by WarenGonzaga** [comment]
Thanks for reporting @francogp I'll look into it.

**Comment by eltonmesquita** [comment]
Hey @WarenGonzaga , that's an easy fix. Just get this [line](https://github.com/animate-css/animate.css/blob/main/postcss.config.js#L5) to start with the backtik right above it in this string literal.

**Comment by WarenGonzaga** [comment]
> Hey @WarenGonzaga , that's an easy fix. Just get this [line](https://github.com/animate-css/animate.css/blob/main/postcss.config.js#L5) to start with the backtik right above it in this string literal.

Got it...

**Comment by WarenGonzaga** [comment]
@eltonmesquita close this one also...
