### ISSUE TITLE
v4 iPhone possible issue

### ISSUE THREAD

**Issue by TheMatheMagician-uk** [animate-css/animate.css#1103]
Dear Animate.css

I'm sorry if these isn't an issue, I'm very new to GitHub and quite new to Web Design. This is my first post.

Animate.css v4 works on my computer in both Laptop (Media Query) and Mobile screen sizes (mobile first design) but when I run it on my actual iPhone it doesn't animate. I am using v4.1.0 on iPhone 7 Plus iOS 13.7 (latest). I am using "animate__animated animate__jackInTheBox animate__slower". I also tried a number of the other v4 animations which also worked fine on desktop but not on iPhone.

As an experiment I downgraded to v3 and used "animated bounce" and it worked fine on desktop and iPhone.

Web page - http://www.themathemagician.uk/contact.html (site under construction and very messy)

**Smartphone (please complete the following information):**

- Device: iPhone7 Plus
- OS: 13.7
- Browser Safari
- Version No idea

It's not an important issue for me as I'm just experimenting with web design but I thought I would let you know in case it's important to you.

Keep safe.

Wayne

**Comment by WarenGonzaga** [comment]
Alright thank you for reporting it @TheMatheMagician-uk ... @eltonmesquita can you take a look into it?

**Comment by eltonmesquita** [comment]
@TheMatheMagician-uk , please [see this](https://animate.style/#accessibility). Make sure to check the linked resource.

**Comment by TheMatheMagician-uk** [comment]
Well that's a stupid feature for iPhones to be set as reduced motion as default. Sorry to bother you as it was obviously an Apple issue and not one for you. Thanks and take care.

**Comment by eltonmesquita** [comment]
No problem.

Sorry but this is *not an issue*, it's an accessibility feature and it's actually very important. I hope you don't disable this feature on your website.
