### ISSUE TITLE
Problem with some animations like bounceOutDown and bounceOutRight / WHITE SPACE

### ISSUE THREAD

**Issue by hatredol** [animate-css/animate.css#111]
Hi im having some problems with these animations, the problem is that everytime i run these animations they create extra white space in my webpage.

Example with bounceOutDown
it creates white space at bottom and bounceOutRight has the same behaviour it creates white space outside body or html tag 
![bounceoutdown](https://f.cloud.github.com/assets/4393211/1414918/dfb93b96-3ebc-11e3-913a-a36047d612f2.png)

maybe im doing somthing wrong thanks in advance

**Comment by AndrewLeonardi** [comment]
I am having this same problem. Overflow: Hidden does not prevent it from creating unwanted white space.

**Comment by Josepdal** [comment]
Same here, having problems with these white spaces...

**Comment by eltonmesquita** [comment]
As cited by Daniel, this is something that you have to deal with by yourself. Use `overflow: hidden` on the parent's element so it won't overflow your page. There's no  golden bullet here, it's just good old CSS behavior.
