### ISSUE TITLE
Animate on scroll: Any alternatives to Wow.js/Aos?

### ISSUE THREAD

**Issue by carlo-13** [animate-css/animate.css#1110]
Hi everyone, and thanks a lot for making such an amazing CSS library!

Just like the title says, I am looking to use animate.css on scroll. I used wow.js for a while now, but it hasn’t been updated in years… same for AOS.

The only way I managed to make this work is by using the latest version of animate.compat.css with wow.js… but it’s not ideal.

I just wanted to ask what are your recommendations to use animate.css on scroll? Something that is lightweight, and SEO optimized.

Thanks a lot!

**Comment by RobHowdle** [comment]
> 
> 
> Hi everyone, and thanks a lot for making such an amazing CSS library!
> 
> Just like the title says, I am looking to use animate.css on scroll. I used wow.js for a while now, but it hasn’t been updated in years… same for AOS.
> 
> The only way I managed to make this work is by using the latest version of animate.compat.css with wow.js… but it’s not ideal.
> 
> I just wanted to ask what are your recommendations to use animate.css on scroll? Something that is lightweight, and SEO optimized.
> 
> Thanks a lot!

Following. Used AOS and that was great but when trying to use with a Laravel Blade Page it gives me so many problems weirdly. I'd very much be interested in what you are looking for as well.

**Comment by vujovicigor** [comment]
Here is a simple animate-on-scroll function based on IntersectionObserver and animate.css classes :
https://codepen.io/vujovichigor/pen/KKzBpbV?editors=1010

**Comment by RobHowdle** [comment]
> 
> 
> Here is a simple animate-on-scroll function based on IntersectionObserver and animate.css classes :
> https://codepen.io/vujovichigor/pen/KKzBpbV?editors=1010

I actually managed to get the AOS working within Laravel last night, my issue was the ordering of the scripts weirdly. I'll take a look at this one though as it seems pretty good too :) Always like to keep a log of these things for future projects.
