### ISSUE TITLE
How to add animation in swiper slider?

### ISSUE THREAD

**Issue by rajeshdoot** [animate-css/animate.css#1115]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by eltonmesquita** [comment]
Sorry, we can't provide support for other libraries here. This is an issue tracker for problems and improvements related to the library itself. Please seek help on stackoverflow.
