### ISSUE TITLE
Transform Property Doesn't Work After Using Animate.css

### ISSUE THREAD

**Issue by ApplePieGiraffe** [animate-css/animate.css#1117]
Hi, there!

In a few of my projects, I've noticed that after I animate an element by adding the animation classes from Animate.css to it, I can no longer use the transform property on that element in my own stylesheet (i.e., the transform property in my stylesheet seems to have no effect, even if my stylesheet is linked after the Animate.css stylesheet in my markup).

Is there any reason why that happens? Or am I doing something wrong?

**Comment by eltonmesquita** [comment]
This is the way CSS works. animate.css is just overwriting any previous transform declaration (we use transform in most of the animations). The easy and quick "fix" is to add a wrapper to the element and animate this wrapper instead.

I'm closing this as it's not an issue with the library. I'll try to add a section in the docs with guidelines about this.

**Comment by ApplePieGiraffe** [comment]
Ah, I see.

Sorry to bother you, then.

Thanks for your help!

**Comment by Directory** [comment]
this isnt a fix but if u can use the animateCSS javascript wrapper function the docs suggested. it removes the animation class after the animation ends so the transform styles wont stick. however *while* an animation is playing your transform styles will still get overriden so it may appear to pop in and out of position randomly. i advise the "wrapper" fix.
