### ISSUE TITLE
Animate.css isn't working 

### ISSUE THREAD

**Issue by liadbelad** [animate-css/animate.css#1121]
I tried to use some of the classes and none worked

I made sure that I got the CDN on the head of my HTML which is 
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />

Yes when I refresh the page nothing happens 

I am using Chrome Version 85.0.4183.102 (Official Build) (64-bit) and Windows 7 on a Laptop

**Comment by eltonmesquita** [comment]
Sorry, but it's very hard to help with so little information and **no code** to debug. But anyway, make sure you have followed the [usage instructions](https://animate.style/#usage) and if you're migrating from a previous version make sure to follow the [migration guide](https://animate.style/#migration).

**Comment by eltonmesquita** [comment]
I'm closing this as it's stale.
