### ISSUE TITLE
Dark Mode Option for the Website

### ISSUE THREAD

**Issue by WarenGonzaga** [animate-css/animate.css#1126]
There is PR #1125 which is might suggesting a dark mode option for the documentation site. I don't know if this is necessary but I would like to work on it to add that. However, to add that we need votes for this feature to be added. Just react thumbs up on this Issue and if you have additional suggestion just let us know. Thank you!

Tagging @eltonmesquita and @daneden, what do you think team?

**Comment by eltonmesquita** [comment]
I don't feel the need, but I'd gladly merge a nicely done PR with this. So, feel free to work on that if you want to ;D

**Comment by WarenGonzaga** [comment]
Cheers! @eltonmesquita

**Comment by gurnoor-garry** [comment]
Hey 
I want to work on this issue. Could u please assign it to me??

**Comment by WarenGonzaga** [comment]
> Hey
> I want to work on this issue. Could u please assign it to me??

Currently, in the works...

**Comment by WarenGonzaga** [comment]
Add this to v5 release @eltonmesquita

**Comment by eltonmesquita** [comment]
#1217 Solves this. Did you have a look at it @WarenGonzaga ?

**Comment by WarenGonzaga** [comment]
@eltonmesquita yes that works... I'm gonna improve his PR when I got some time.

**Comment by eltonmesquita** [comment]
No need for hurry, I'll leave a review there soon, but when you have time, it'd be nice to suggest improvements and share your ideas there, so no work is wasted 😉

**Comment by WarenGonzaga** [comment]
@eltonmesquita assign @mehmetsagir for the task as he has the PR.

**Comment by eltonmesquita** [comment]
I can't do that as he's not in the org nor this conversation.

**Comment by WarenGonzaga** [comment]
Hi @eltonmesquita, what's the plan here? It seems both is not responding?

**Comment by mehmetsagir** [comment]
@WarenGonzaga I made the final edits for the PR(#1217 ) and sent it. However, I have not yet received a response.

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga I made the final edits for the PR(#1217 ) and sent it. However, I have not yet received a response. I can completely take over the dark mode feature if you want.

Yeah, all good I'm waiting for @eltonmesquita decision.

**Comment by eltonmesquita** [comment]
Solved by #1217 .
