### ISSUE TITLE
Custom '--animate-delay' is not working

### ISSUE THREAD

**Issue by dunker1304** [animate-css/animate.css#1141]
- When I customize **--animate-delay** using VueJS and NextJS, I found something missing in **animate.css**

![Screen Shot 2020-10-08 at 15 55 39](https://user-images.githubusercontent.com/42232002/95437328-0daefb00-097f-11eb-9073-7439c6091033.png)

- I think this codes missing variable for **animation-delay** to customize delay time, so I added 2 lines like this, and it worked:

![Screen Shot 2020-10-08 at 15 55 57](https://user-images.githubusercontent.com/42232002/95437741-9168e780-097f-11eb-8851-ea65dba8cbf5.png)

- Am I right, or we have another solution?

**Thank you**

**Comment by eltonmesquita** [comment]
I understand your concern, but the `--animate-delay` property is used by the delay classes only. We shouldn't add it to the `animated` class as it would add a delay to every animation.

Any custom need should be handled by the developer as you just did. I'm closing this.

**Comment by goodpixels** [comment]
@eltonmesquita I think @dunker1304 is right on this.

I can see no reason why this variable should not be exposed. This is exactly how I want to use it.

If it clashes with the internal delay variable, then at least provide another one.

And while all of this can be customised by a developer, I feel like the overall appeal of `animate.css` is it's drag-and-drop ease of use.

IMHO this issue should be re-opened and this should be implemented.

Best regards

**Comment by WarenGonzaga** [comment]
Hi @goodpixels, I got your point... I'm the author of CSS utilities... I'm gonna PR an update for this.

As I understand if the delay animation property is not defined it can cause issue so provide default one.
So the developer just plug and play the animate.css is that correct?

Let me know thanks!

**Comment by eltonmesquita** [comment]
@goodpixels, the variables are for the global delay classes, as is [outlined in the docs](https://animate.style/#utilities). You can change them per element like this:
```css
.my-element {
  --animate-delay: 0.5s;
}
```
This way, the new value would be modified only for the `.my-element` and its descendants and the delay classes would respond to the ratio set to the var, 0.5s (`animate__delay-2s` becomes a 1s delay, `animate__delay-3s` 1.5s and so on). 

It would probably cause lot's of problems if we were to set a delay in every animation just so the dev could override them later. It wouldn't bring any real benefit as it is as much work as just adding the `animation-delay` property to each element you need.

So @WarenGonzaga, there's no need for a PR related to this.

**Comment by WarenGonzaga** [comment]
> @goodpixels, the variables are for the global delay classes, as is [outlined in the docs](https://animate.style/#utilities). You can change them per element like this:
> 
> ```css
> .my-element {
>   --animate-delay: 0.5s;
> }
> ```
> 
> This way, the new value would be modified only for the `.my-element` and its descendants and the delay classes would respond to the ratio set to the var, 0.5s (`animate__delay-2s` becomes a 1s delay, `animate__delay-3s` 1.5s and so on).
> 
> It would probably cause lot's of problems if we were to set a delay in every animation just so the dev could override them later. It wouldn't bring any real benefit as it is as much work as just adding the `animation-delay` property to each element you need.
> 
> So @WarenGonzaga, there's no need for a PR related to this.

Got it @eltonmesquita... make sense

**Comment by goodpixels** [comment]
Hi @WarenGonzaga, @eltonmesquita  thank you for such a quick reply.

This is for example how I use `--animate-duration` in my React app:

```
const styles = {
    '--animate-duration': `${i}s`
};

<h1
    className="animate__animated animate__fadeInUp"
    style={styles}
>Heading</h1>
```

I would expect the same to work for the delay:

```
const styles = {
    '--animate-duration': `${i}s`,
    '--animate-delay': `${i+1}s`
};

<h1
    className="animate__animated animate__fadeInUp"
    style={styles}
>Heading</h1>
```

But because this variable is not referenced in `animate__animated` class, I have to do this instead:

```
const styles = {
    '--animate-duration': `${i}s`,
    animationDelay: `${i+1}s`
};

<h1
    className="animate__animated animate__fadeInUp"
    style={styles}
>Heading</h1>
```

The difference between the two is that in the latter I am __actually__ overwriting the `animation-delay` CSS property on the element, rather than the CSS variable.

The desired behaviour can indeed be achieved without making any changes to `animate.css`, but I don't really understand the reasoning behind omitting this particular variable but providing others.

Like I said in my previous post, I think the beauty of `animate.css` it it's ease of use and I can't see a reason why this variable should not be exposed.

Best regards

**Comment by eltonmesquita** [comment]
I do understand your concern, but like I told before these variables were made to support the delay classes only. If we were to apply a delay to every class it would be counter-intuitive and very confusing to most of the users.

I'm still against the proposal as it wouldn't bring many benefits to the overall user. Unless more people bring this up, I'm likely to avoid implementing it in the future.
