### ISSUE TITLE
Animate.css not work on my Mac 

### ISSUE THREAD

**Issue by liangwuweb** [animate-css/animate.css#1146]
**Describe the bug** I just find out that the animate.css does not work on my Mac, I tried out fireFox, safari, and chrome, none of them works. Then I tried it on my windows 10 machine, it works perfectly. 

**To Reproduce** The problem is that the animate.css just does not work. When I go to _animate.style_ website, all the examples just do not animate. 

**Here is my mac system info:**
<img width="576" alt="Screen Shot 2020-10-12 at 12 07 51 PM" src="https://user-images.githubusercontent.com/44330488/95773159-92ea2680-0c83-11eb-844a-0b2b58aa8ea4.png">

   **The browsers I've tried**
   - chrome 
   Version [85.0.4183.121 (Official Build) (64-bit)]
  - Safari 
   Version [13.1.2 (14609.3.5.1.5)]
  - Firefox 
   Version [81.0 (64-bit)]

**Comment by eltonmesquita** [comment]
Please see in the best practice section [here] (https://animate.style/#best-practices) the section "Don't disable the prefers-reduced-motion media query".

Also, there should be a warning in your screen about that in the website.

**Comment by liangwuweb** [comment]
Oh, yes, I did see the warning on the site now. Thank you so much, I just turn off the reduce-motion on my Mac, and it works perfectly!
