### ISSUE TITLE
 Why. Current version is not working 

### ISSUE THREAD

**Issue by HThangDev** [animate-css/animate.css#1200]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by WarenGonzaga** [comment]
Your report is lack of information... can you give as steps to reproduce the issue? also can you provide a codepen version of the issue so we can take a look into it. Thanks.

**Comment by eltonmesquita** [comment]
I just closed this as there's on info. I might reopen this if @HThangDev give us some proper description of what's wrong. But first, make sure you read the whole documentation.
