### ISSUE TITLE
Animations not working on initial page display, works after page refresh.

### ISSUE THREAD

**Issue by WayneHiller** [animate-css/animate.css#1201]
I have a Blazor WebAssembly app and have included animate.css 4.1.1.  The first time a page is displayed no animations work (animate something on button click etc). There are no errors in the dev tools and I can see the animate.css file loaded. If I then refresh the page all the animations work from then on.

**Comment by eltonmesquita** [comment]
Sorry, but it's really hard to help with so little information. Could you share a reduced case somewhere? (code sandbox, codepen, etc)

**Comment by WayneHiller** [comment]
I don't know why but it seems to be working now. Very strange. If it happens again I will investigate more.
