### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'return'

### ISSUE THREAD

**Issue by vipera7** [animate-css/animate.css#1211]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Init the function

I created the function as in the documentation : 

```
const animateCSS = (element, animation, prefix = 'animate__') =>
  // We create a Promise and return it
  return new Promise((resolve, reject) => {
    const animationName = `${prefix}${animation}`;
    const node = document.querySelector(element);

    node.classList.add(`${prefix}animated`, animationName);

    // When the animation ends, we clean the classes and resolve the Promise
    function handleAnimationEnd(event) {
      event.stopPropagation();
      node.classList.remove(`${prefix}animated`, animationName);
      resolve('Animation ended');
    }

    node.addEventListener('animationend', handleAnimationEnd, {once: true});
  });
```

**Expected behavior** A clear and concise description of what you expected to happen.
No error output

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome, firefox
- Version: Version 87.0.4280.141 (Build officiel) (64 bits), 84.0.2 (64 bits)

**Comment by plantdink** [comment]
https://github.com/animate-css/animate.css/pull/1209#issue-550736795

This will fix the issue you are having. 

Just remove the return on this line, everything else is correct.

```
const animateCSS = (element, animation, prefix = 'animate__') =>
  // We create a Promise and return it
  new Promise((resolve, reject) => {
    const animationName = `${prefix}${animation}`;
    const node = document.querySelector(element);
```
