### ISSUE TITLE
RE: Additive Animations - Animations API

### ISSUE THREAD

**Issue by LukeTOBrien** [animate-css/animate.css#1223]
Hi chaps,

Awhile ago I mentioned about a [Additive Animation CSS proposal](https://github.com/animate-css/animate.css/issues/1010).  
I have just found a [new article on the subject](https://css-tricks.com/additive-animation-web-animations-api/), it seems that Firefox nightly and Chrome Canary do have additive animation.

I just wanted to share it with you folk as I know you are enthusiastic, perhaps you can have a read and even do some experiments using those browsers mentioned.

Luke

**Comment by WarenGonzaga** [comment]
Awesome let us take a look and discuss this. Hi @eltonmesquita is this a good time to add this to v5?

**Comment by eltonmesquita** [comment]
Thanks for the heads up but no, we're not ready for this. We should wait until all major browsers support the CSS version for at least 2 versions. When adding this we'll have to provide a progressive away, so we're still a long way for that.

**Comment by WarenGonzaga** [comment]
> Thanks for the heads up but no, we're not ready for this. We should wait until all major browsers support the CSS version for at least 2 versions. When adding this we'll have to provide a progressive away, so we're still a long way for that.

I guess we can take note of this internally... and take a look back soon.
