### ISSUE TITLE
animate not work correctly when rerender

### ISSUE THREAD

**Issue by xkungfu** [animate-css/animate.css#1224]
I have button group component.
the group 1 have 3 buttons.
the group 2 have 5 buttons.
when click one button of group 1 , the component rerendered to group 2.
but, the animation only work on the last two button.
animation not work on the first 3 buttons.

how to resolve it?

thanks!

**Comment by xkungfu** [comment]
thanks!

**Comment by amanRT** [comment]
Ok....I am working on that.

**Comment by eltonmesquita** [comment]
Sorry, but there's no way we can help this way. Can you please create a small reduced case on codepen, with a proper description of the issue and share it here?

**Comment by eltonmesquita** [comment]
I'm closing this at it's stake and has not enough information.
