### ISSUE TITLE
Animation opacity overrides the one i need on IOS

### ISSUE THREAD

**Issue by vandelpavel** [animate-css/animate.css#1228]
I'm currently using quasar framework and i'm trying to animate an element when i click on a button.
In order to hide my element i'm using the on mounted hook to set (as style) 0 opacity.
Then when i click the button i'll add the animated class and let's say.. FadeInDown.
Immediately afther that i set the opacity to ' ' in order do delete the opacity from the style.

On windows works great problems comes when working on ios. I'v noticed that in the newer versions (like 14.4) works as expected but in older the element keeps a strange opacity. It looks like it has something like 0.3.

Problems goes awai when i disable the opacity inside the animation class.

Also noticed that using a class with more specificity doesn't work on IOS.

1. add opacity 0 (from style)
2. trigger animation by applying animated, animation-class and set opacity to ' '

**Expected behavior**
The element should be invisible from the beginning and after the animation it sould keep the initial opacity.
![image](https://user-images.githubusercontent.com/61196133/107064347-acd3ea00-67db-11eb-8131-5ce243f03076.png)

**Behavior**
After the animation the element has a really low opacity.
![image](https://user-images.githubusercontent.com/61196133/107063955-451d9f00-67db-11eb-99d5-42e6c1ab5aad.png)

**Smartphone (please complete the following information):**

- Device: iPhone6
- OS: <12
- Browser safari

**My code**
```vue
<script>
export default {
  name: 'Test',
  mounted() {
    const el = document.querySelector('.square');
    el.style.opacity = 0;
  },
  methods: {
    animate: function () {
      const el = document.querySelector('.square');

      const classes = ['animated', 'fadeInDown'];
      el.classList.add(...classes);
      el.style.opacity = '';
    },
  },
};
</script>

<template>
  <q-page class="row justify-center">
    <div class="square" />
    <div>
      <q-btn label="trigger animation" @click="animate()" />
    </div>
  </q-page>
</template>

<style scoped lang="scss">
.square {
  background-color: red;
  height: 100px;
  margin: 24px;
  width: 100px;
}
</style>

```

**Comment by eltonmesquita** [comment]
Try using the `visibility: hidden` property and switching it to `visibility: visible`. Also setting opacity to 1 makes more sense than setting it to an empty string.

**Comment by vandelpavel** [comment]
Empty strings will remove the inline property so in other therms it reset the initial one. Assume you want to animate an element with 0.5 opacity. Using this method will override the default one. I'll try visibility.
