### ISSUE TITLE
How to use animate.css with Nuxt.js

### ISSUE THREAD

**Issue by gilles6** [animate-css/animate.css#1234]
How to configure Nuxt.js to be able to use animate.css ?

**Comment by WarenGonzaga** [comment]
Installing it with Nuxt might be tricky... this one https://github.com/neneos/nuxt-animate.css/ might be helpful but I'm not recommending might be it uses the outdated version of animate.css

**Comment by rommyarb** [comment]
To be able to use **Utility classes**, define the 'animate.min.css' file in your `nuxt.config.js`
```js
export default {
  // ...
  css: ['animate.css/animate.min.css'] // Not 'animate.css/animate.compat.css'
  // ...
}
```

Now you can use utility classes,
```html
<div class="animate__animated animate__bounce animate__delay-2s">Example</div>
```

**Comment by swapnilnandgave** [comment]
How can we use that for page transitions?

**Comment by scolastico** [comment]
Same question here: How can we use that for page transitions?
