### ISSUE TITLE
Sass Version for 4.?

### ISSUE THREAD

**Issue by zedjr** [animate-css/animate.css#1235]
Is there a sass version for animate css 4.?. I see a version for older 3.? done by a few others but none for this current library. Any plans for this in future.

**Comment by eltonmesquita** [comment]
Please see this [comment](https://github.com/animate-css/animate.css/pull/277#issuecomment-406763275) and if you got a few minutes, read all the issue so you can understand our motivation.

I'm closing this as it's solved already.
