### ISSUE TITLE
webpack 5 Integration issues for animate.css

### ISSUE THREAD

**Issue by SatishChandraPalakoti** [animate-css/animate.css#1252]
**Describe the bug** Module build fails

**To Reproduce** Execute the webpack command to run the project:

**Expected behavior** No errors to be yielded and project compiled successfully

**Screenshots** 

**`Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: The target selector was not found.
Use "@extend .animated !optional" to avoid this error.

   ╷
10 │         @extend .animated;
   │         ^^^^^^^^^^^^^^^^^
   ╵`**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome,FireFox
 
**Additional context** Migrating my project to webpack5 from v3 of webpack. I encounter this above specific error while executing the project via webpack. The build fails and yields these errors.

**Comment by eltonmesquita** [comment]
Sorry but this is not an animate.css issue but a webpack configuration one. You can try to find help on stackoverflow as the chances are higher on getting some help on that.

I'm closing this as it's unrelated to this library.
