### ISSUE TITLE
all effects fire at page load ready

### ISSUE THREAD

**Issue by anas57687** [animate-css/animate.css#1256]
Hi friends, 
I can't know how to submit this problem to you if this bad user experience or bug.
but when add animate class to any element even element at the end of page the effect fires after page load without scrolling to the element, so that meaning effects wouldn't appear correctly.
thanks a lot for this brilliant library.

**Comment by TheFakeCake** [comment]
This is the intended behavior if you just add the classes to your elements.

If you want dynamic behavior, like firing the animation when an element becomes visible (while scolling for example), you need some javascript to dynamicaly add the classes.

**Comment by eltonmesquita** [comment]
Thanks for
