### ISSUE TITLE
Adding a new animation.

### ISSUE THREAD

**Issue by Rishi1314** [animate-css/animate.css#1258]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Rishi1314** [comment]
Hey, I'm just starting my open source contribution path and was hoping if someone could guild me.
I know html and css and basics(animation) of js.
I was hoping to add a new animation, which is levitation or floating.

**Comment by eltonmesquita** [comment]
Hey @Rishi1314, please check the [contribution section on docs ](https://animate.style/#license-contributing) and the [contributing guide](https://github.com/animate-css/animate.css/blob/main/CONTRIBUTING.md).

We do need help on issues and PR reviewing, so feel free to help where you feel more comfortable. I'm closing this to keep the repo tidy.
