### ISSUE TITLE
LESS version?

### ISSUE THREAD

**Issue by kevsmt** [animate-css/animate.css#126]
Hi, do u happen to have a LESS version?

.myclass {
   .animate;
   .fadeInRight;
}

it would be awesome..

**Comment by royduin** [comment]
@JvanderHeide, awesome! Thanks!

**Comment by Mayccoll** [comment]
https://github.com/Mayccoll/animate.less

**Comment by arcanedev-maroc** [comment]
https://github.com/machito/animate.less
