### ISSUE TITLE
how can use the animate  end and delay 2s then start? not use js.

### ISSUE THREAD

**Issue by wangzl8128** [animate-css/animate.css#1316]

**Comment by Shubham56-droid** [comment]
you can use animation-delay:2s;  in CSS.

**Comment by eMeRiKa13** [comment]
Hi,

I'm trying to add a delay between two repetitions in an infinite loop. The documentation indicates:

```
Intervals between repeats
Unfortunately, this isn't possible with pure CSS right now. You have to use Javascript to achieve this result.
```

So I'm curious how you made it worked with "animation-delay:2s; in CSS" ?

Thanks

**Comment by warengonzaga** [comment]
> Hi,
> 
> I'm trying to add a delay between two repetitions in an infinite loop. The documentation indicates:
> 
> ```
> Intervals between repeats
> Unfortunately, this isn't possible with pure CSS right now. You have to use Javascript to achieve this result.
> ```
> 
> So I'm curious how you made it worked with "animation-delay:2s; in CSS" ?
> 
> Thanks

I think you can achieve this by doing a separate animation one without delay and the one with delay.

**Comment by eMeRiKa13** [comment]
> > Hi,
> > I'm trying to add a delay between two repetitions in an infinite loop. The documentation indicates:
> > ```
> > Intervals between repeats
> > Unfortunately, this isn't possible with pure CSS right now. You have to use Javascript to achieve this result.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I'm curious how you made it worked with "animation-delay:2s; in CSS" ?
> > Thanks
> 
> I think you can achieve this by doing a separate animation one without delay and the one with delay.

Thanks for your answer. With this method, I will be able to have two repetitions, not an infinite animation with a pause each time between the animations?

**Comment by KodingKhurram** [comment]
Seems interesting,

But there is no way to achieve this without the help of JS, with JS my friend you can do many things.

**Comment by warengonzaga** [comment]
> > > Hi,
> > > I'm trying to add a delay between two repetitions in an infinite loop. The documentation indicates:
> > > ```
> > > Intervals between repeats
> > > Unfortunately, this isn't possible with pure CSS right now. You have to use Javascript to achieve this result.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So I'm curious how you made it worked with "animation-delay:2s; in CSS" ?
> > > Thanks
> > 
> > 
> > I think you can achieve this by doing a separate animation one without delay and the one with delay.
> 
> Thanks for your answer. With this method, I will be able to have two repetitions, not an infinite animation with a pause each time between the animations?

looks like you are referring to chain animation? we're still thinking of adding this to the build.

**Comment by warengonzaga** [comment]
> Seems interesting,
> 
> But there is no way to achieve this without the help of JS, with JS my friend you can do many things.

yup, you can control the animate.css animation with help of JS.

**Comment by KodingKhurram** [comment]
> > Seems interesting,
> > But there is no way to achieve this without the help of JS, with JS my friend you can do many things.
> 
> yup, you can control the animate.css animation with help of JS.

Yes sir, 

@eMeRiKa13 If you need chain of animation you can use "animationend" property in JS and just play with it.

Look at some [examples](https://animate-dynamic.ga/examples.php) here.
