### ISSUE TITLE
How do I animate on Scroll (Hugo site)

### ISSUE THREAD

**Issue by georgeheginbotham** [animate-css/animate.css#1326]
Hey guys I have animations imported with animate.css (https://animate.style/ 1) but I’d like them to activate on scroll. I’ve struggled to find a solid piece of information that can help me so I’m hoping you guys could help fill the gap.

You can see the animation in effect when you disable and enable it by the “Our Process” section on the header tag (when you disable and enable it in inspect mode). How do I animate it on scroll, could someone provide me with a plugin/ piece of code I can use?

![Screenshot 2021-07-06 233956](https://user-images.githubusercontent.com/68346866/124705593-33f5cd00-def6-11eb-9e55-cc2cb261122c.png)

Site: gofishvideo.com

My sites using Jquery, so how would I enable the feature with Jquey, do I edit the Jquery file, make a new one, make a JS file, etc, then how do I call that code within the Index/partial files?

P.S. I don’t mind paying for help implementing these custom animations

**Comment by eltonmesquita** [comment]
Pease see #1006. As it's unrelated to to library and we can't provide much help, I'm closing this.
