### ISSUE TITLE
Migration from 3.xx to 4 - animations does not work

### ISSUE THREAD

**Issue by Halfdann** [animate-css/animate.css#1327]
Hello,

Animations working as usual with:
https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css
On a simple div element using classes: animated slideInLeft

Switching to v4.:
this https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.compat.css or
https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css 

Tested on the same alement before - remove the previous classes and try:
animate__fadeIn = does not work
animate__fadeInDown = does not work
animate__bounceIn = works 

I have not found any help sofar, but also any dependencies which I would missing in order to support this.
But as the bounce effect works and the rest not I am realyl confused :-O
Thanks

**Comment by eltonmesquita** [comment]
Sorry, but it is very hard to help with so little info and no live, reduced case. If you can get it live on codepen or somewhere else hit us back so we can have a look at it.

**Comment by eltonmesquita** [comment]
Closing this as we've got no answer.
