### ISSUE TITLE
Problem with normalize

### ISSUE THREAD

**Issue by Leman214** [animate-css/animate.css#1332]
I have an issue with normalize, because i wrote that:

* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

and it has no effect, look:

![image](https://user-images.githubusercontent.com/55116683/126101653-a9609ff4-bb6a-4e91-9d39-fa0782798b3f.png)

someone can help me, please?

pd sory about my english, im from argentina

**Comment by eltonmesquita** [comment]
Sorry, but I think you created the issue in the wrong repo. Also, you'll get more help on a site like stackoverflow not the library's issue tracker which is dedicated to issues with the library itself, not usage. When you ask for help on stackoverflow, make sure you give more details a be as descriptive as you get. Using Google Translator is a good call if you're not confident in your English skills.

I'm closing this as it's not related to the library itself.
