### ISSUE TITLE
SlideInDown Safari 13

### ISSUE THREAD

**Issue by MattiaDucci** [animate-css/animate.css#1343]
When I try to apply the `slideInDown` class to my DOM element in Safari 13 the animation works, but at the end the animated element disappears. In Google Chrome this doesn't happen. Instead the `fadeInDown` animation works fine even in Safari. 
Thank you

**Comment by eltonmesquita** [comment]
A few things:
- [ ] Make sure that you read the [Best practices](https://animate.style/#docSection-best-practices) section, mainly the **Mind the initial and final state of your elements** part.
- [ ] **Check if this happens on [our website](https://animate.style/).**

If the bug shows on our website too, please report it here. If it doesn't happen on our website, it's probably a usage issue and you should seek help on StackOverflow with a reduced case as this issue tracker focus only on bugs and feature requests for the library and unfortunately, we can't help everyone here.

**Comment by eltonmesquita** [comment]
Hey @MattiaDucci , I'm leaning on closing this as we didn't get any response.

**Comment by eltonmesquita** [comment]
I'm closing it as I've got no response.
