### ISSUE TITLE
css modules

### ISSUE THREAD

**Issue by Zzdl** [animate-css/animate.css#1345]
how i can use that in css modules?

**Comment by eltonmesquita** [comment]
It should work the same way as the [CSS modules documentation outlines.](https://github.com/css-modules/css-modules) You just have to make sure that you're using both animate classes including the prefix as [our documentation details](https://animate.style/#usage).

**Comment by Zzdl** [comment]
> It should work the same way as the [CSS modules documentation outlines.](https://github.com/css-modules/css-modules) You just have to make sure that you're using both animate classes including the prefix as [our documentation details](https://animate.style/#usage).

**Comment by Zzdl** [comment]
> It should work the same way as the [CSS modules documentation outlines.](https://github.com/css-modules/css-modules) You just have to make sure that you're using both animate classes including the prefix as [our documentation details](https://animate.style/#usage).

OK. I've got it. Thank you!
