### ISSUE TITLE
Stuck when 2 animation classes at same element

### ISSUE THREAD

**Issue by clifftm** [animate-css/animate.css#1370]
Hello, and sorry for my bad english =)

When adding at least two animation classes to an element, some variations of them cause an animation to stuck, and even not playing the second. I'v made an [example](https://codepen.io/clf/pen/jOwRoPK). 

As you can see, when i add, for example rubberBand and after 1 second wobble, all 2 animations play correctly each after another.
But otherwise when 1st animation is wobble, and after comes rubberBand, the second not plays at all. Even after clearing classes to default state ( class = "square red animate__animated" ) by pressing button and adding wobble again, it won't play at all.

I know about fast remove\add a same class and force to update DOM with void div.offsetWidth;  or setTimeout(). Then a first animation plays again ( see Example 10) , but that doesn't fix a stuck of second animation.

Maybe i don't understand something, but i'm really confused with such behaviour, when some combinations are working, but other not.

By the way, look at Example 11. I'v replaced classList.add with
```
div.style["animation-name"] = "rubberBand";
setTimeout(()=>{div.style["animation-name"] = "bounce"; },1000)
```
and that is correct behaviour.

sad that the most used animation 
`animate__bounceOutLeft and then animate__bounceInRight ` not working, but
`animate__bounceInRight and then animate__bounceOutLeft` is working...

Probably there is a way to fix that but with classes?

**Comment by KodingKhurram** [comment]
@clifftm here is what you wanted [the_pen](https://codepen.io/KodingKhurram/pen/oNepgxd) 

Feel free to share your thoughts :)
