### ISSUE TITLE
GitHub Discussions for Animate.css

### ISSUE THREAD

**Issue by WarenGonzaga** [animate-css/animate.css#1375]
Hello, animate.css community!

I would like to know if it is good to add a discussions section here in our repository for questions, suggestions, ideas, showcases, and more. Instead of using third-party services just to create a forum-like environment.

Anyone? 

cc: @eltonmesquita

**Comment by KodingKhurram** [comment]
Yes, seems interesting, as people can post their stuffs there, posting it in issues will be off topic, for ideas, suggestions, etc. Good idea.

**Comment by ashutosh61973** [comment]
good idea

**Comment by WarenGonzaga** [comment]
> I think it might be a good idea to have a trial. As we lack ~manpower~ people-power to keep our eyes all the time on it, it can become a ~no-man-land~ no-people-land. My guess is that most of the discussion will be around basic CSS usage, as most of the issues are. If this becomes true it'd be better to direct people to StackOverflow which makes more sense.
> 
> I'll try to have a good look at it in the next few days so we can be sure that we'll use it properly.

Let's be clear before they use our discussion tab. I agree with you, the forum would definitely be all about CSS usage with animate.css and if the question or the topic is beyond what supposed to be we'll ask them to search on StackOverflow instead.

**Comment by eltonmesquita** [comment]
I just enabled the discussion feature. You can [check it here](https://github.com/animate-css/animate.css/discussions). I hope things go smoothly.

**Comment by WarenGonzaga** [comment]
> I just enabled the discussion feature. You can [check it here](https://github.com/animate-css/animate.css/discussions). I hope things go smoothly.

Do I have some permission to set it up? I love to do it...
