### ISSUE TITLE
Auto  Delay:500

### ISSUE THREAD

**Issue by thefubon** [animate-css/animate.css#1379]
Please tell me how to make elements appear one after the other after 3 seconds, just like it is done in UIKIT ?
https://getuikit.com/docs/scrollspy#set-code-cls-code-option-per-target

**Comment by KodingKhurram** [comment]
class="animate__animated animate__bounce animation-delay-3s" in element, or in css --animation-delay : 3s;, or if you need more delay you can use javascript/jquery to stall the animation, then add the classes.

**Comment by thefubon** [comment]
How to make it appear when only in the visibility of the scrolling screen was.

**Comment by KodingKhurram** [comment]
That's a different thing, animate.css is like a static animation library, you can use javascript/jquery to determine when the element appears on screen then add animation classes.

**Comment by WarenGonzaga** [comment]
Hi @thefubon, yes I would advise combining it with JS. Also, you are correct @KodingKhurram animate.css is a static animation library. If you want advanced animation I would advise using JS animation or a combination of animate.css with JS.

**Comment by KodingKhurram** [comment]
Hello, @WarenGonzaga 

I 'am working on a small library, combining JavaScript/jQuery and animate.css, it's almost ready for first use, but I don't know where to post it, should I create an issue for it, or will you make a new channel for discussion and stuffs.

**Comment by WarenGonzaga** [comment]
> Hello, @WarenGonzaga 
> 
> I 'am working on a small library, combining JavaScript/jQuery and animate.css, it's almost ready for first use, but I don't know where to post it, should I create an issue for it, or will you make a new channel for discussion and stuffs.

You can create a new issue for now as we are finalizing to add discussion or not.

cc:@eltonmesquita @daneden

**Comment by WarenGonzaga** [comment]
Hi @eltonmesquita I guess it is now good to close this issue.
