### ISSUE TITLE
Animate.css-Dynamic, combining JavaScript/jQuery and Animate.css

### ISSUE THREAD

**Issue by KodingKhurram** [animate-css/animate.css#1382]
Hello guys,

I have been using animate.css library for academic project from few months, it's amazing animation library and very easy to use, but the thing is it's a static library and you don't have control on animations as such, you have to do some external work on it using JS/jQuery, I did the same for my academic project.

Then I thought of generalizing it and making it like a library, so I tried, I call it Animate.css-Dynamic.

GitHub :-  [animate.css-dynamic](https://github.com/KodingKhurram/animate.css-dynamic)
Demo :- [animate-dynamic.ga](http://animate-dynamic.ga)

What you guys think about it..?

Feel free to share your thoughts....

And sorry animate.css for copying your template xD.

**Comment by KodingKhurram** [comment]
@WarenGonzaga, good to hear that, I am looking up to it :)

While I was working on this, I realized lot of things can be done, I don't know how difficult it would be, with respect to implementation, but don't cry before try.

First of all, I want to make this fully stable to use, then there are some plans on "utility functions", and as you see "custom animations" is an open and clear feature now, for which we can just tweak a little bit, combine some animations, play with some CSS, and create new animations.

I will be looking up to get input from you guys, and I will be happy if I can help in any way to contribute. 🙂

**Comment by KodingKhurram** [comment]
Here is [v2.9.2](https://github.com/KodingKhurram/animate.css-dynamic/releases/tag/v2.9.2) just a little step towards optimization.

**Comment by KodingKhurram** [comment]
Version [v2.13.5](https://github.com/KodingKhurram/animate.css-dynamic/releases/tag/v2.13.5) a custom animation and more.

**Comment by warengonzaga** [comment]
I think we can now close this @eltonmesquita, feel free to post this on showcase in the Discussions @KodingKhurram
