### ISSUE TITLE
Add "animate__animated" when you copy-paste on https://animate.style

### ISSUE THREAD

**Issue by bdmariobd** [animate-css/animate.css#1398]
It should help a bit.
Also, I wanted to request adding CDN information to this repository "readme".
Cool library BTW!

**Comment by WarenGonzaga** [comment]
Hi @bdmariobd actually you can check out the [official website](https://animate.style/#usage).

We have a CDN in the installation section. Also, the README file on this repo keeps it as simple as possible.
All the information can be found on the website.

Can you close this? @eltonmesquita

**Comment by WarenGonzaga** [comment]
Wait, let me create a PR for your request @bdmariobd for a moment.
