### ISSUE TITLE
Update NPM-package so it correctly reflects class names

### ISSUE THREAD

**Issue by Rvervuurt** [animate-css/animate.css#1406]
I added Animate.css through NPM today, and couldn't figure out why the animations weren't working. I was doing everything as I written on [the NPM page](https://www.npmjs.com/package/animate.css/v/3.7.0).

However, what I found out when I went to the demo page, you changed the classes that have to be added to the elements you want to animate.
It's actually the first step after including the css-files:

> Add the class `animated` to the element you want to animate. You may also want to include the class `infinite` for an infinite loop.

But it should say:
> Add the class `animate__animated` to the element you want to animate. You may also want to include the class `animate__infinite` for an infinite loop.

And below that, all the animation classes should also get update to reflect the `animate__` part.
I highly doubt everything else on the page is up-to-date, but I have not had a chance to check everything.

I know all of this also can be read on animate.style, but I was trying to set it up from the NPM page and it didn't work until I checked out the demo page.

Just an idea of course! A quick solution would maybe be to only show setup on the NPM-package and link to the documentation on animate.style?

**Comment by eltonmesquita** [comment]
Hey @Rvervuurt, the page you're pointing at is for an older version - v3.7.0 - and can't be changed. [The latest published version on npm has the current documentation](https://www.npmjs.com/package/animate.css).

I'm closing this as it's not an issue.
