### ISSUE TITLE
Animation trigger on hover

### ISSUE THREAD

**Issue by Cool-Scratcher** [animate-css/animate.css#1410]
**Is your feature request related to a problem? Please describe.** There's currently no way that I know of in animate.css to trigger an animation on text or an element being hovered upon.

**Describe the solution you'd like** Could this be a feature within the library itself? (Sorry if I seem kind of clueless, I'm only 13 and not very familiar with the ins and outs of coding. I'm learning, though 😛)

**Comment by KodingKhurram** [comment]
Hello @Cool-Scratcher , I know animate.css doesn't provide such feature now, but you can simply do this.
`.element:hover{
  animation: bounce; /* referring directly to the animation's @keyframe declaration */
}` 
or use JavaScript/jQuery for the same.

You may like to have a look at [this](https://animate-dynamic.ga) library.

Happy learning :)

**Comment by WarenGonzaga** [comment]
I guess I can add this feature, and I will call it triggers? 🤔

**Comment by nascarjake** [comment]
Looking forward to this update - would love a simple way to apply hover animations

**Comment by WarenGonzaga** [comment]
> Looking forward to this update - would love a simple way to apply hover animations

Let me see what I can do...

**Comment by eltonmesquita** [comment]
I don't like the idea, as different from transitions, animations don't play very well with hover state, as they don't resume and rewind the animations gracefully.  There are a few ways to do this but most of them are hacky or include js, which is out of this library's context. Not only that, most of our animations aren't fit for hover state as most are long and too "abrupt" for that.

I'll keep this open to hear from you guys and see if I missed some points.

**Comment by warengonzaga** [comment]
> I don't like the idea, as different from transitions, animations don't play very well with hover state, as they don't resume and rewind the animations gracefully. There are a few ways to do this but most of them are hacky or include js, which is out of this library's context. Not only that, most of our animations aren't fit for hover state as most are long and too "abrupt" for that.
> 
> I'll keep this open to hear from you guys and see if I missed some points.

Agree on this, we should think about this as we have some limitation with CSS.
