### ISSUE TITLE
Multiple animations in sequence

### ISSUE THREAD

**Issue by Nickyg001** [animate-css/animate.css#1418]
I state that I do not know if currently it can already be done, I have not been able to find anything about this thing.

I wish I could apply sequential animations spaced out over time. example:

The first "animate__backInRight" animation starts
At the end of the backInRight animation, the second animation starts
"animate__tada", it is possible to apply a repeat_3 or infinite or other functionality to the second animation

**Comment by KodingKhurram** [comment]
Hello @Nickyg001 
This seems out of reach using only animate.css library, you can achieve this with JavaScript/jQuery 
like this `$(elem).addClass("animate__animated animate__backInRight"); elem.addEventListener('animationend', () => { $(elem).removeClass("animate__animated animate__backInRight"); $(elem).addClass("animate__animated animate__tada animate__repeat-3"); }`

Example [pen](https://codepen.io/KodingKhurram/pen/bGrXxmo).

You can have a look at [this](https://animate-dynamic.ga/#custom) where you can get 2 animations with just 1 class `aniCus_OutIn-backInRight-tada` but not sure how you can achieve `repeat-3` :)
