### ISSUE TITLE
Detect animation ending

### ISSUE THREAD

**Issue by pfinkbeiner** [animate-css/animate.css#143]
I would rather use the jQuery `.on()` listner instead of `.one()`. Animation could be triggered multiple times then, for example if you add an animation on `.hover()`.

It's just a README.md related _improvement_ …
`$('#yourElement').on('webkitAnimationEnd mozAnimationEnd oAnimationEnd animationEnd', doSomething());`

**Comment by wildskyf** [comment]
How can I detect animation end without using jQuery?
