### ISSUE TITLE
Some animations not working

### ISSUE THREAD

**Issue by N3rdP1um23** [animate-css/animate.css#1442]
**Describe the bug**
I've just upgraded a project from v3 to v4 and followed the migration steps on the site. When using the `rubberBand` animation, v4 no longer works correctly (don't execute at all) along with a few other "Attention seekers" animations. 

**To Reproduce**
Including sample JSFiddles with sample code to demonstrate the issue

- **rubberBand** - not working - https://jsfiddle.net/20az1y6p/
- **Flash** - working - https://jsfiddle.net/xb1k4woe/

**Expected behavior**
The rubberBand animations should be triggered and execute like on [animate](https://animate.style/) site.

**Screenshots**
None

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser Edge
- Version 98.0.1100.3

**Additional context**
See above linked JSFiddles for examples.
- Tested in above mentioned Edge and Chrome 97.0.4692.71 and issue still exists
- When testing the animations on the site, there isn't any issues with rubberBand or the other mentioned animations below
- The issue only exists with the `animate.css` file, switching back to the `animate.compat.css` file resolves the issue
- Additional animations that aren't working
  - bounce
  - pulse
  - shakeX
  - shakeY
  - headShake
  - swing
  - tada
  - wobble
  - jello
  - heartBeat

**Comment by N3rdP1um23** [comment]
Okay, I've played around with it a little more and have found some additional info online. I also realized I was using the wrong element when testing 🙃 haha

Anyways, for the `rubberBand` JSFiddle, if you add `display: inline-block;` to the span, the animation works without issue. I found this out after stumbling across the following
- https://stackoverflow.com/a/32991609
- https://stackoverflow.com/q/4121843

Another odd thing I found, when you change it to `display: block;` it performs a completely different animation.

I'll leave it open for now just in case this is something that could be added to the docs or potentially addressed in the classes itself? If you'd rather close off the issue, feel free!

Thanks again for this awesome animation package!

**Comment by KodingKhurram** [comment]
Hello @N3rdP1um23 

This kinda behavior is already addressed [in gotchas](https://animate.style/#gotchas) of official site.

Yaah, `display: block` is makes it an entire block in the page just like a `div` and the width is `100%` to the parent element so the animation looks weird because it is executed on the whole block no matter inner content.

**Comment by N3rdP1um23** [comment]
Ahh _gotcha_ haha and oh man, I don't know how I completely missed that. I think when I was scrolling through the docs, I got to the "Don't disable the prefers-reduced-motion media query" section and saw the "Usage with Javascript" and jumped right over that "Gotchas", my bad.

Thanks again for that! And yeah, that makes complete sense :)
