### ISSUE TITLE
hinge triggers immediately

### ISSUE THREAD

**Issue by Cyberchicken** [animate-css/animate.css#1462]
Applying "animate__hinge" class to an element triggers the animation as soon as the page is loaded, 
while the documentation suggests that the trigger should be the "animate__animated" class.

The demo works beacause it adds both classes at once.

My setup to reproduce on Google Chrome Version 97.0.4692.71 (Official Build) (64-bit):
```
<!doctype html><head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/></head>
<div class="animate__hinge"><img src="https://picsum.photos/300/200"></div>
```

Expected behavior: no animation.

The few other animations I tried worked as I expected.
Did I get something wrong?

I will experiment with Animate.css-Dynamic, with using the bare keyframes definitions and by slicing down Animate.css to the minimum components.

Thank you

**Comment by eltonmesquita** [comment]
See https://github.com/animate-css/animate.css/discussions/1453

**Comment by Cyberchicken** [comment]
I think I deserve an answer: if "animate__animated" is not the trigger, what's its purpose?
