### ISSUE TITLE
官网为什么打不开了？

### ISSUE THREAD

**Issue by ponysb** [animate-css/animate.css#1567]
### Describe The Bug

官网打不开了在哪可以看效果的类名？

**Comment by warengonzaga** [comment]
hey @ponysb the website is working normally what do you see on your end? Any error?

**Comment by warengonzaga** [comment]
@eltonmesquita feel free to close this thanks!

**Comment by halo951** [comment]
> @eltonmesquita feel free to close this thanks!

hallo, the website really can't be opened,  i think the reason is "DNS_PROBE_FINISHED_NXDOMAIN", it may be due to DNS configuration problems or fillwall in china.

**Comment by ponysb** [comment]
> 嘿@ponysb网站运行正常 你看到了什么？有什么错误吗？

网络在中国区内打不开，我用了vpn把网络代理到国外可以就打开了

**Comment by penggang-home** [comment]
![image](https://user-images.githubusercontent.com/55438345/177464267-63d1e55f-ceae-4122-be43-b9ccb3467f81.png)
中国区域内无法访问

**Comment by DuckBurnIncense** [comment]
国内有时要用魔法

**Comment by eltonmesquita** [comment]
The website is working properly and I don't think there is much to do about this now. Thanks for reporting!

**Comment by LIUSHUAI2018** [comment]
科学上网我也打不开了

**Comment by LIUSHUAI2018** [comment]
Google can be opened, but this website can not be opened

**Comment by DuckBurnIncense** [comment]
> 科学上网我也打不开了

![图像 001](https://user-images.githubusercontent.com/87637270/183245409-51bff339-ecb9-45ae-9d0b-df2b288122a7.png)

我这不需要科学上网也能访问哦 (没有缓存) ^(*￣(oo)￣)^

**Comment by DuckBurnIncense** [comment]
实在不行的话给你个解决方案 @LIUSHUAI2018  用 git 把这个仓库克隆下来, 然后在 /docs 目录下用 node 等工具搭建一个简易服务器, 打开后就是 animate.css 官网了, 亲测有效.

参考步骤:

Step 1: 

```
git clone https://github.com/animate-css/animate.css.git
```

Step 2:

```
cd animate.css/docs
```

Step 3:

```
npm install serve -g
```

Step 4:

```
serve
```

Step 5:

在你的浏览器打开 http://localhost:3000 

结束

**Comment by LIUSHUAI2018** [comment]
> 不能的话给你一个解决方案@LIUSHUAI2018 用git把这个​​仓库下来，然后在/docs下用节点等工具就是一个简单的目录，打开后亲测有效。
> 
> 参考步骤：
> 
> 步骤1：
> 
> ```
> git clone https://github.com/animate-css/animate.css.git
> ```
> 
> 第2步：
> 
> ```
> cd animate.css/docs
> ```
> 
> 第 3 步：
> 
> ```
> npm install serve -g
> ```
> 
> 第4步：
> 
> ```
> serve
> ```
> 
> 第 5 步：
> 
> 在你的浏览器中打开http://localhost:3000
> 
> 结束
> 
> ![图像 002](https://user-images.githubusercontent.com/87637270/183245917-0a1cd38f-c4d1-4307-acee-4d127ce453a3.png)

谢谢提醒，看到你的网页之后我觉得有可能是dns的问题，我自定义了dns为8.8.8.8或114.114.114.114就可以访问了
