### ISSUE TITLE
Is there a way to control the amplitude of a animation？👀

### ISSUE THREAD

**Issue by Lukrisum** [animate-css/animate.css#1568]
### Is your feature request related to a problem? Please describe.

I've recently been trying to use Animate.css to make a "like" animation, using animate-pulse, but I found that it scaled a bit smaller than I expected, so I want to ask if Animate.css provides A way to set the magnitude of the animations

### Describe the solution you'd like.

 (by setting percentages etc.)

### Describe alternatives you've considered.

null

**Comment by warengonzaga** [comment]
Duplicate of #1009, thanks for reporting!

**Comment by Lukrisum** [comment]
Sorry I didn't search carefully. Looks like it's already on the to-do list, thanks for you reply !
