### ISSUE TITLE
Pulse animation bug

### ISSUE THREAD

**Issue by AlexRMU** [animate-css/animate.css#1570]
### Describe The Bug

Pulse animation is used on one element on the page. When it starts, all the letters on the page seem to change the font, and return when it ends. There is nothing in css and if you zoom in, everything is fine.

### Screenshots

![image](https://user-images.githubusercontent.com/61969794/178436174-5187f7ed-41eb-4361-b1a5-d3c9f2a418a4.png)
![image](https://user-images.githubusercontent.com/61969794/178436217-066dae99-462b-42e7-9c9f-b195b1694b5b.png)

### Desktop

Version: latest
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Additional Context

Perhaps this is a browser bug.

**Comment by warengonzaga** [comment]
Any codepen or related to repreduce the issue?

**Comment by AlexRMU** [comment]
https://codesandbox.io/s/ecstatic-haslett-jietfo

**Comment by warengonzaga** [comment]
I see, it gitters @AlexRMU

**Comment by eltonmesquita** [comment]
This isn't exactly a bug, but a browser peculiarity related to animating/rendering elements. In the past, this sort of problem was massive and depending on the browser, it would make the pages unusable 😢.  To make things bearable you'd have to resort to some nasty and crazy hacks. Things improved a lot and now everything is mostly stable in every browser out there, but we can still see some remaining issues from that time. This is one example.

There is nothing the library itself can do about this. It's a browser rendering issue and if it's getting in your way the best advice I can give is to do a good research about how browsers render pages and search for some "ancient" hacks on how to fix it. This probably won't have any serious side effect in any page anywhere, so I don't think there is much to worry about it.

**Comment by AlexRMU** [comment]
👍
