### ISSUE TITLE
在 animate__fadeInUp 动画和其他多个动画下会导致 backdrop-filter 滤镜失效

### ISSUE THREAD

**Issue by ponysb** [animate-css/animate.css#1604]
### Describe The Bug

<div style="padding: 0 15px 0 15px;
        height: 36px;
        border-radius: 50px;
        background: rgba(205, 205, 205, 0.3);
        box-shadow: 3px 5px 10px 5px rgb(0 0 0 / 10%);
        backdrop-filter: saturate(200%) blur(5px);
        margin-left: 12px;
        margin-bottom: 20px;
    display: flex;"></div>

在 animate__fadeInUp 动画下以上代码中的 backdrop-filter 样式失效了

**Comment by warengonzaga** [comment]
hey @ponysb can you use English for reporting? Also, provide the replication steps you are reporting.
