### ISSUE TITLE
Add triggers utility classes on interaction events.

### ISSUE THREAD

**Issue by AlizerUncaged** [animate-css/animate.css#1627]
### Is your feature request related to a problem? Please describe.

I always had to use JS in order to make the animations work if the mouse hovers.

### Describe the solution you'd like.

Maybe add a utility class that marks the animation to only work on specific events? Such as `onclick`, `onmouseenter` and so on.

### Describe alternatives you've considered.

Currently I'm adding and removing classes via JS.

### Additional Context

None.

**Comment by eltonmesquita** [comment]
Sorry, but besides a few cases, there's no way to achieve this with only CSS, js is always needed.  Not only that, our animations aren't suited to short and quick interactions such as transitions. 

I'm closing this as it won't be added to this library.
