### ISSUE TITLE
Man

### ISSUE THREAD

**Issue by abisan96** [animate-css/animate.css#1653]
Smart love angry fight

**Comment by abisan96** [comment]
![image](https://user-images.githubusercontent.com/123060038/218410269-e7920ae5-4784-4904-8455-f5cd6f846f09.png) love fight 4k

**Comment by jaydeepkhatri** [comment]
Hi @abisan96 

Please make sure you follow the [Code of Conduct](https://github.com/animate-css/animate.css/blob/main/CODE_OF_CONDUCT.md) & Don't spam with on a public repo.

I ask you to close the issue.

Thanks. :)
