### ISSUE TITLE
Not working on Google Chrome v=103 / Linux

### ISSUE THREAD

**Issue by Raf-sns** [animate-css/animate.css#1654]
### Describe The Bug

Hi !
I was trying the latest minified version 4.1.1,
I had to remove this code to get animations:

 `@media (prefers-reduced-motion: reduce), print
.animate__animated {
    /* -webkit-animation-duration: 1ms!important; */
    /* animation-duration: 1ms!important; */
    /* -webkit-animation-iteration-count: 1!important; */
    /* animation-iteration-count: 1!important; */
    /* -webkit-transition-duration: 1ms!important; */
    /* transition-duration: 1ms!important; */
}`
Hoping to help...

### Steps To Reproduce

1. raw the v4.1.1 animate.min.css lib.
2. include stylesheet 
3. add clases to an element 

### Expected Behavior

an animation

### Desktop

Linux / Fedora v.33
Google Chrome v103

**Comment by eltonmesquita** [comment]
From the docs:
> Since version 3.7.0 Animate.css supports the prefers-reduced-motion media query which disables animations based on the OS system's preference on supporting browsers (most current browsers support it). This is a critical accessibility feature and should never be disabled! This is built into browsers to help people with vestibular and seizure disorders. You can read more about it [here](https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/).

I'm closing this as it's not an issue.
