### ISSUE TITLE
Implement animate on scroll

### ISSUE THREAD

**Issue by IndigoSoftwares21** [animate-css/animate.css#1659]
### Is your feature request related to a problem? Please describe.

I a trying to play animations on scroll but it does not work

### Describe the solution you'd like.

 I would like that a feature wheby we can animate item on scroll be added

### Describe alternatives you've considered.

AOS LBRARY

**Comment by IndigoSoftwares21** [comment]
Thank you 😊

**Comment by eltonmesquita** [comment]
There's no plan for adding javascript to the library at the moment. Closing it as it has been settled before
