### ISSUE TITLE
iOS 14 support

### ISSUE THREAD

**Issue by dijkermans** [animate-css/animate.css#1660]
### Describe The Bug

Hi,

Looks like iOS14 is not supported because none of the animations are shown. Is there a way to make it compatible using e.g. a polyfill?

Thanks.

Regards, J

### Expected Behavior

Animations

### Smartphone

ipad 2017 / iOS 14.6

**Comment by dijkermans** [comment]
Solved. Reduced Motion was enabled on this device.

**Comment by warengonzaga** [comment]
Can we close this @eltonmesquita
