### ISSUE TITLE
Request for a forwards fill css class parameter

### ISSUE THREAD

**Issue by Sartharian** [animate-css/animate.css#1663]
### Is your feature request related to a problem? Please describe.

I've been searching/reading like an hawk-eyed person around docs for an option to keep/maintain element animated "at the end of animation values" but i didn't find anything helpful about that.

### Describe the solution you'd like.

this link shows the exact result what i expect from a feature request.
https://www.w3schools.com/css/tryit.asp?filename=trycss3_animation_fill-mode
it can be implemented by creating a "animation-forwards" utility class with the fill mode css attribute into "!important" value.

### Describe alternatives you've considered.

So, the only way to have this get working is set an "hardcoded" option called "forwards", to keep the element at the end of animation assigment. Also creating a @keyframes with animation classes too, but do this make no sense. (Reinventing wheel time?).

### Additional Context

Sorry if this feature is included and i can't see on the docs at the time of posting this.
Thanks in advance.

**Comment by crileyy** [comment]
@Sartharian since this currently isn't a feature, have you found a way to do this? I'm not sure I understand the alternative method you described.

**Comment by Sartharian** [comment]
My apologies, but actually i migrate my code project from CSS animation implementation to JS. =) (due to client's requirements).
