### ISSUE TITLE
Duplicated property name in animation.css

### ISSUE THREAD

**Issue by leslie555** [animate-css/animate.css#1665]
### Describe The Bug

When I copied the `animation.css` file to my local, I just found there are some duplicated property name. Please see the attachment.  We could set default value for `var`.

### Screenshots

![image](https://user-images.githubusercontent.com/40735433/226270201-df0378a6-2b35-4c1d-b3b4-090d0245f8cb.png)

**Comment by JatinBawne** [comment]
I would be happy to work in this issue.
kindly assign it to me.

**Comment by Kedarnath-Rothe** [comment]
Pease assign this issue to me

**Comment by eltonmesquita** [comment]
Not a bug, it's an intended fallback for when css custom properties (css variables) are not supported. Maybe we just don't need this anymore.
