### ISSUE TITLE
Animate only if i hit a specific section

### ISSUE THREAD

**Issue by innocentrixphilippines** [animate-css/animate.css#1667]
### Is your feature request related to a problem? Please describe.

Animate only if i hit a specific section

### Describe the solution you'd like.

Animate only if i hit a specific section

### Describe alternatives you've considered.

Animate only if i hit a specific section

**Comment by emilsrits** [comment]
You can already do it easily with IntersectionObserver or checking element offsetTop and window page offset...

**Comment by eltonmesquita** [comment]
animate.css won't provide js features in its core library. Closing it
