### ISSUE TITLE
Adding AOS 

### ISSUE THREAD

**Issue by yasaminashoori** [animate-css/animate.css#1669]
### Is your feature request related to a problem? Please describe.

I think it would be a great idea to have AOS too in this repo, it is kind of an animation and it will complete this repo.

### Describe the solution you'd like.

Maybe more detailed about  AOS: when and how to use it.

### Describe alternatives you've considered.

Delay time, duration and the other things

**Comment by eltonmesquita** [comment]
Thanks for the suggestion but we've got no plans on merging other libraries or to add any js support for now
