### ISSUE TITLE
Keep the element at the end of its animation values

### ISSUE THREAD

**Issue by crileyy** [animate-css/animate.css#1672]
### Is your feature request related to a problem? Please describe.

Currently, I'm using the slideOutRight and slideOutLeft animations, but after the animation finishes, the elements return to their original position, which causes a flicker in my use case. Is there a way to maintain the end position/state of the element after the animation? I'm thinking of something like `animation-fill-mode: 'forwards'`

### Describe the solution you'd like.

An option to have the element stay where it is at the end of the animation, like setting `animation-fill-mode: 'forwards'`.

### Describe alternatives you've considered.

Nothing seems to work to do this.

**Comment by Sartharian** [comment]
haha, perhaps u didn't read the doc before: the default fill mode animation is "both", so u must define ur own 'forwards' fill mode class implementation. See my answer on prev post =)
