### ISSUE TITLE
copy button to copy code by just one click

### ISSUE THREAD

**Issue by weberankit** [animate-css/animate.css#1674]
### Is your feature request related to a problem? Please describe.

_basically if we provide copy button then users just only need to press the button to copy the code so I think it provides an ease to the users
![image](https://github.com/animate-css/animate.css/assets/94105514/50fabac4-cc1b-437a-8bd0-7f3b8d48b68a)

### Describe the solution you'd like.

I will use the button to copy the code and after the code is copied it will show copied for a sec

### Describe alternatives you've considered.

no alternative

### Additional Context

plz assigned it to me so that I can start working

**Comment by eKeiran** [comment]
Hi @warengonzaga can this be assigned to me? Would love to contribute!

**Comment by weberankit** [comment]
I'm already working on it plz work on another issue

**Comment by eltonmesquita** [comment]
Heya, that's a good suggestion @weberankit. No need to tackle this @eKeiran and @weberankit as we'll probably switch for a proper doc website soon, which should bring these features automatically

**Comment by warengonzaga** [comment]
This is a good addition, actually as @eltonmesquita mentioned there's a pending plan to improve and update the current documentation site.

**Comment by weberankit** [comment]
@eltonmesquita @warengonzaga 
#1676 I know that you are working on new documentation and you don't need this right now but believe that it takes me hours to complete this so I thought to make PR.

**Comment by warengonzaga** [comment]
@eltonmesquita what do you think?

**Comment by dpvasani** [comment]
Assign to me

**Comment by dpvasani** [comment]
#1676 

//HTML

<button id="copyButton" onclick="copyCode()">Copy</button>
<pre id="codeBlock">
// Your code goes here
</pre>


//JS

// JavaScript
function copyCode() {
  // Get the code block element
  var codeBlock = document.getElementById("codeBlock");

  // Create a range to select the code block
  var range = document.createRange();
  range.selectNode(codeBlock);

  // Select the code block
  window.getSelection().removeAllRanges();
  window.getSelection().addRange(range);

  try {
    // Copy the selected code
    var successful = document.execCommand('copy');
    var message = successful ? 'Copied!' : 'Unable to copy!';
    console.log(message);
  } catch (err) {
    console.log('Unable to copy!');
  }

  // Remove the selection
  window.getSelection().removeAllRanges();

  // Show "Copied" message briefly
  var copyButton = document.getElementById("copyButton");
  copyButton.innerHTML = "Copied!";
  setTimeout(function() {
    copyButton.innerHTML = "Copy";
  }, 1000);
}

**Comment by Niranjan-Kumar-Singh** [comment]
Could you please assign this issue to me.

**Comment by prithvi5481** [comment]
Please assign this issue to me.

**Comment by dejanheroxd** [comment]
Hey there i just had an idea about allowing users to customize the copied code before copying. We can add a small input field beside the code snippet, where users can make minor adjustments or add comments before clicking the "Copy" button. This way they can change the code to their use case, so it is more versatile

**Comment by Jay90123** [comment]
Can you please issue this to me!?
I have come up with a solution

**Comment by eltonmesquita** [comment]
Sorry, but I prefer to spend all the time/resources into moving to the new docs
