### ISSUE TITLE
Link to Hippocratic license triggers antivirus phishing alert

### ISSUE THREAD

**Issue by ikender** [animate-css/animate.css#1679]
### Describe The Bug

Ironically, my antivirus (AVG) triggers a "phishing" alert on the Hippocratic license pages

While this may be a false positive, I know nothing about the site and am not about to report it to AVG as a false positive.  But I figured I would let you know so you can decide to look into it or not

### Steps To Reproduce

install AVG antivirus
go to the url by clicking the link on the license section of the readme.md file
see popup from AVG saying you can't go

### Screenshots

![image](https://github.com/animate-css/animate.css/assets/5349370/53d43304-c2aa-40da-8f6c-714104835368)

**Comment by eltonmesquita** [comment]
As you can [see here](https://www.virustotal.com/gui/url/7f6863273af30abd1f09899c3d0a4747025f2c0a109edea79c975e37e6658c70), the website is secure. I think AVG is triggering a false positive. Would you mind to check if this is still true @ikender? Unfortunately I can't install AVG anywhere
