### ISSUE TITLE
blank space in the document section

### ISSUE THREAD

**Issue by prashikk** [animate-css/animate.css#1712]
### documentation's index section could be improved.
once you scroll down the index used for the document's reference or topics walkthrough, they are gone. if a user need to go to a particular section he has to scroll all the way up and click on the particular section.

https://github.com/animate-css/animate.css/assets/91461422/422b388e-1cf7-46d5-b058-4949b0f7601e

### solution could be.

first of of all the "index" should be sandwich between "Documentation" heading and its main content. this will make the content in the document section to be centre align. when you scroll the index should stick on top and have a parallex effect (to which section you are on).

### alternatives solution could be.

the index could also be kept floating but one major problem would also be that this will not solve the problem which is wastage of space on right side.

**Comment by eltonmesquita** [comment]
Thanks for raising this. It makes a lot of sense, but at the moment we're moving away from this custom docs building, so I prefer to put the effort on moving to the new docs than to get this right with our custom one.

Thanks for the effort! Hopefully we'll see a new improved version in the next few months 🤞
