### ISSUE TITLE
 [FEATURE] Menu Icon Doesn't Hide After Click and Should Change to Cross Icon

### ISSUE THREAD

**Issue by Bittukr7479** [animate-css/animate.css#1713]
### Is your feature request related to a problem? Please describe.

I encountered an issue with the menu icon on the website. After clicking the menu icon, it doesn't hide as expected, and it should also change into a cross icon.

### Describe the solution you'd like.

Open the website in your browser.
Switch to the responsive mode.
Scroll down the page.
Click on the menu icon.

https://github.com/animate-css/animate.css/assets/123286618/9c39d434-47f9-4ff3-8786-b2b76e67996f

### Describe alternatives you've considered.

The menu icon should hide after being clicked.
The menu icon should change into a cross icon to indicate that the menu is open.

**Comment by eltonmesquita** [comment]
Sorry, this won't be needed anymore as we're moving away from the custom docs

**Comment by Bittukr7479** [comment]
Okh @eltonmesquita , thanks for reply.

**Comment by warengonzaga** [comment]
> Sorry, this won't be needed anymore as we're moving away from the custom docs

Do we have any progress about this?
