### ISSUE TITLE
License mismatch in github repo source and npmjs

### ISSUE THREAD

**Issue by bpraharaj** [animate-css/animate.css#1722]
Hello, We noticed a difference in license attribution in your source repo https://github.com/animate-css/animate.css/blob/main/LICENSE (Hippocratic) and which is mentioned in npmjs https://www.npmjs.com/package/animate.css/v/4.1.0 (MIT)

Need to have a clarification/understanding before I can start using it.  Looking for consistency with it.

**Comment by VaclavElias** [comment]
Please double check. Old version(s) are MIT. The latest version(s) are what they are https://github.com/animate-css/animate.css/issues/1364#issuecomment-932814739. So if you need MIT, you need to figure out which version.
