### ISSUE TITLE
fadeInRightBig causes horizontal scrollbar.

### ISSUE THREAD

**Issue by m-vdv** [animate-css/animate.css#198]
The fadeInRightBig animation triggers a horizontal scrollbar (tested in Chrome) and issues on mobile browsers (android /ios).

See (and choose fadeInRightBig:
http://daneden.github.io/animate.css/

Any idea how to fix this?

**Comment by rushi** [comment]
Thanks @IliaIdakiev that helped!

**Comment by IliaIdakiev** [comment]
@rushi You are welcome :)

**Comment by hasan-r0ny** [comment]
Add these code to the parent element's class.


	max-width: 100%;
	overflow: hidden;

**Comment by MikeGolf83** [comment]
the problem with this code is that it messes with my background-attachment:fixed code, does anyone know another way to solve it?

**Comment by rmoorman** [comment]
@MikeGolf83 you could try to apply some wrapping. I guess the background-attachment fixed issue is related to the fact that you apply the max-width and overflow to the same element that has the background-attachment supplied. Maybe wrapping the element to animate within another element and applying the rules @hasan-r0ny suggested to it could lead to a solution for your situation.

**Comment by MikeGolf83** [comment]
@rmoorman thank you for your answer! I solved it by applying the overflow to the body instead of the html element. Hopefully it won't mess with other things! Thanks again for your help.

**Comment by ghasemi1994** [comment]
@IliaIdakiev 
Im using overfllow-x:hidden but my scroll vertical goes right

**Comment by eltonmesquita** [comment]
Add the element you're animating to a parent (like a div) and set overflow: hidden and max-width: 100% on the parent.

**Comment by ghasemi1994** [comment]
@eltonmesquita thank you

**Comment by digitlimit** [comment]
I have same issue.  Resolved by applying the overflow to the body instead of the HTML element
  
   html{
        max-width: 100% !important;
        overflow: hidden !important;
    }

Like @manuel-grondona asked, would this cause any unforeseen issues? 
So far I have not noticed any issue.

**Comment by gajendrapalkaushik** [comment]
body{
       max-width: 100% !important;
       overflow: hidden !important;
}

this doesn't work , instead the page becomes short or say right side of page get fit into the page like we resized it.   

please anyone help me

**Comment by eltonmesquita** [comment]
> Add the element you're animating to a parent (like a div) and set overflow: hidden and max-width: 100% on the parent.

This is the safest way to handle this type of situation. Please see [this article](https://css-tricks.com/almanac/properties/o/overflow/) to make the best use of the `overflow` property.
