### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by ghost** [animate-css/animate.css#213]
It would be nice if you could have gulp support ...as most of us use it for developing these days...

**Comment by soulhunter1987** [comment]
The same problem, most libraries today support both

**Comment by erikdonohoo** [comment]
Over a year later, the tide has turned in favor of gulp I would say.  :)

**Comment by george3447** [comment]
+1

**Comment by miticv** [comment]
+1

**Comment by arcanedev-maroc** [comment]
Gulp :+1:

**Comment by tarciozemel** [comment]
@pyros2097 @daneden 

![gulp-better-grunt](https://cloud.githubusercontent.com/assets/133777/11373331/dcaae5d8-92b8-11e5-82ae-0dcc973c7241.png)

**Comment by pyros2097** [comment]
Wow! :walking: its been more than a year and gulp has emerged. Gulp :100:

**Comment by erilyth** [comment]
gulp +1

**Comment by biwin** [comment]
+1 📢

**Comment by kafeltz** [comment]
gulp :+1:
