### ISSUE TITLE
entrance bugs?

### ISSUE THREAD

**Issue by Voorhuis** [animate-css/animate.css#234]
I'm using animate.css in combination with fullPage.js. When I scroll to a new page I use a jQuery callback to addclass. For example: 'animated fadeInUp'.

The issue is: I experience buggy behaviour in browsers like Chrome and FF. Like div's showing up in a flash before disappearing and then fading in. Sometimes the fullPage.js needs a little to calculate the height of a page to position the content right. While that is happening the div needs to stay hidden for about 0.5s.

How do I avoid this short flash of the div in the endstate at the beginning of the animation?

**Comment by bs-thomas** [comment]
I have the same issue here

**Comment by PaulRBerg** [comment]
+1
