### ISSUE TITLE
Hide to show animation?

### ISSUE THREAD

**Issue by KingYes** [animate-css/animate.css#266]
Hey @daneden you did very nice work here ! :)

I just want to combine your CSS with [Waypoint](http://imakewebthings.com/jquery-waypoints/) jQuery plugin. So I want the element with my custom CSS for handle Waypoint get `display: none` and when I use with your animation `in` like `fadeIn` It's get in my page.

What I get right now, I see the element, and I fire the `.animated` and It's hide and show with fade. That's not good.

Can I do that?

Best,
Yakir.

**Comment by FNGR2911** [comment]
I can't get it to work with visibility: hidden

I got an element (#logo) which i wan't to fadeInUp after scrolling 15px with jquery. So in CSS #logo got visibility: hidden and I add the classes animated and fadeInUp after scrolling. But nothing happens.. I really don't know what I'm doing wrong?!?

```
	#logo {
		position: absolute;
		top: 10px;
		left: 20px;
		width: auto;
		height: 40px;
		visibility: hidden;
}

	$(window).scroll(function() {    
	    var scroll = $(window).scrollTop();
	
	    if (scroll >= 15) {
	        $("#long-logo").addClass("bounceInDown");
	    } else {
		    $("#long-logo").removeClass("bounceInDown");
	    }
	});
```

**Comment by eltonmesquita** [comment]
You've got to set the visibility to visible or the element won't be visible. Just add it in your css in the class bounceInDown. Animate.css won't do it for you.
