### ISSUE TITLE
animate.css not working properly in Firefox (latest release)

### ISSUE THREAD

**Issue by alaahag** [animate-css/animate.css#269]
hi guys,

I tried to use animate.css in Modal bootstrap (latest release)

the effect is working in all browsers except Firefox

example code of modal here that I used:
(in firefox not working and showing the default fade down effect for modal)

<div class="modal bounceIn rotateInDownLeft fade" tabindex="-1" role="dialog" aria-hidden="true">

any idea how can I fix that?

thanks

**Comment by tienvx** [comment]
Just follow the example in http://daneden.github.io/animate.css/

```javascript
$('#animationSandbox').removeClass().addClass(x + ' animated').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
      $(this).removeClass();
    });
```

The same idea, but the author add 'one' method to detect that animated is end, and then remove all animated classes. This code work well on latest firefox.

**Comment by KasunWeerakoon** [comment]
Some animations doesn't work properly as it visible in the example. (https://daneden.github.io/animate.css/). Is there right way to apply these animations?
