### ISSUE TITLE
Cannot combine different effects

### ISSUE THREAD

**Issue by PandaWhisperer** [animate-css/animate.css#271]
I have a "help" screen in my app that I'm showing when the user presses the `h` or `?` key. It's an overlay with a higher z-index, and I want to use animate.css to animate the entrance and disappearance of that element.

However, when I put both a `fadeIn...` and `fadeOut...` class on my element, only the latter animation takes effect, and when I try and reveal that element, it actually appears for a split second and then disappears.

How can I apply the `fadeIn` animated when showing the element, and `fadeOut` when hiding it?

**Comment by eabigelow** [comment]
PandaWhisperer could you put an example here of how you accomplished this using a CSS transition? Thank you!

**Comment by PandaWhisperer** [comment]
@eabigelow this was almost 5 years ago. Sorry, but I do not remember what I did.
