### ISSUE TITLE
Causes fixed positioned elements jump when scrolling in Chrome

### ISSUE THREAD

**Issue by foofighter123** [animate-css/animate.css#274]
I have fixed header and when animations of other elements start the header jumps when scrolling. It happens in Chrome, in Firefox it works just fine.

**Comment by neoone256** [comment]
Thank you!

**Comment by hugohcn** [comment]
Heyyy @foofighter123 ...

Really thank you. :D

**Comment by rifatwahid** [comment]
we have noted this issue and we will update it in next version.

**Comment by SteeltideTM** [comment]
@rifatwahid This problem persists until today

**Comment by darrenbarklie** [comment]
Thanks for this @foofighter123 - really helped me out despite a number of failed attempts to fix.

**Comment by Chetnaa** [comment]
I have used the solution provided by you but my issue is still not resolved

**Comment by svetadobricic** [comment]
Great!

**Comment by bharathism04** [comment]
> I got it... Added this to the header:
> 
> ```
> -webkit-transform: translate3d(0, 0, 0);
> transform : translate3d(0, 0, 0);
> ```
> This resolves the issue

Hi, i will add this style for which element?

**Comment by Frankj1995** [comment]
This worked for me, thank you so much!! Was causing me a lot of grief.

**Comment by thexmanxyz** [comment]
The `transform` fix did not work for me for BS `fixed-top`. But I found a working solution: `body { overflow-x: hidden; }` which prevents interferences of floating menus or navigation bar with the actual animation.

**Comment by ivkodev** [comment]
> The CSS `transform` fix did not work for me for BS `fixed-top`. But I found a working solution: `body { overflow-x: hidden; }` which prevents interferences of floating menus or navigation bar with the actual animation.

THANK YOU!
