### ISSUE TITLE
updated to latest from 3.1.0 and fadeInUp and other are very different

### ISSUE THREAD

**Issue by ghost** [animate-css/animate.css#288]
Best example is the fadeIn from any direction.  3.1.0 they are nice and subtle.  However the latest version flies in like its crazy!  

Are these issues or are these the new changes?

**Comment by kentcdodds** [comment]
I animate my views into place and I relied on the `20px` animation being quite subtle. But now that it's animated relative to its own size, it's a huge animation (the view can be hundreds of pixels tall). How can I make this be more subtle?

**Comment by kentcdodds** [comment]
P.S. I would consider that a breaking change... Do you disagree or does this project not follow semver?

**Comment by daneden** [comment]
@kentcdodds fair point. Sorry about that. In the upcoming Sass version, I’m planning on introducing configuration variables, one of which would let you determine whether transformations are relative or absolute in relation to the size of the element.

**Comment by eltonmesquita** [comment]
Hey @daneden, how are you planning this? I was thinking about it and the obvious conclusion was to use mixins. But I don't know if it is a good approach as its use is not that obvious...

If you're willing to share how you're pretending to do this I might try to help to rewrite animate.css so we can get the new version out faster.
