### ISSUE TITLE
ios8 flipOutY not working right

### ISSUE THREAD

**Issue by flawedCanis** [animate-css/animate.css#298]
Helo guys,

In ios8 for iphone, the flipOutY isn't behaving properly, instead of the usual flip and fadeOut it usually does, it is starts flipping with a weird flickering ( box appearing and disappearing multiple times per second while doing the flip ).

In ios8 for the ipad, the entire box disappears while the entire effect is being done.

If you guys have any updated for this, I would be really grateful.
Regards.

**Comment by meetbryce** [comment]
I didn't have any luck with your suggestions Oryan (thanks for sharing though). Not sure why I didn't get anywhere...

I opted to just rip out the troublesome animations using the code below:

```javascript
isIOS8 = function() {
  var deviceAgent;
  deviceAgent = navigator.userAgent.toLowerCase();
  return /(iphone|ipod|ipad) os 8_/.test(deviceAgent);
};

if (isIOS8()) {
  $('.flip').addClass('zoomIn').removeClass('flip');
  $('.flipInY').addClass('zoomIn').removeClass('flipInY');
  $('.flipInX').addClass('zoomIn').removeClass('flipInX');
  $('.flipOutY').addClass('zoomIn').removeClass('flipOutY');
  $('.flipOutX').addClass('zoomIn').removeClass('flipOutX');
};
```

_nb: the if statement needs to be wrapped in a closure if your script isn't loaded at the bottom of the page (or is loaded async) and replace zoomIn with whatever animation you want to replace the flips with._

**Comment by lemmycaution** [comment]
Hi there, just fyi @oryan's solution have worked for me too, adding `-webkit-backface-visibility: hidden;` with `  -webkit-transform: translate3d(0,0,0);` both animated element and it's container resolves that error.
