### ISSUE TITLE
Downloading animate.css using bower fails

### ISSUE THREAD

**Issue by erf** [animate-css/animate.css#302]
I get the following error: 

"bower animate#\*             EMALFORMED Failed to read /var/folders/_h/nmmm9stx66d41cphf5bswbl80000gn/T/erf/bower/animate-36852-Sa2SfF/bower.json"

"Additional error details: Unexpected token }"

**Comment by nonamez** [comment]
Same thing:

> bower EMALFORMED    Failed to read /var/folders/l5/m34msbh94wldj819fqszqz1r0000gn/T/bower/a2a424217f809672e8fe80ddeab36781-1242-uIld23/bower.json
> 
> Additional error details:
> Unexpected token }

Tried bower update, bower install,  bower install animate, bower install --save animate
