### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by dicesales** [animate-css/animate.css#66]
Some animations gives a blank white space when fired. 
eg. bounceIn, fadeInLeft

**Comment by gleenk** [comment]
Same problem here on Safari, actually it's visible on my testingarea at studiotoia.testingarea.it.
It generates white space at the end after firing wow+animate.css

**Comment by eltonmesquita** [comment]
Fix your markup, [you've got strayed tags](https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&doc=http%3A%2F%2Fstudiotoia.testingarea.it%2F).

**Comment by gleenk** [comment]
I fixed all error caused by closing tags but problem still exist

**Comment by eltonmesquita** [comment]
Still, this is probably an animate.css issue. You'll have to isolate the problem to try to discover the real problem. Maybe it is a browser bug, but it doesn't look to be related to animate.css at all.

**Comment by gleenk** [comment]
I tried to remove section by section but problem is not markup or else, it's an animate.css or wow.js problem, nothing else :)

**Comment by mmguide2003** [comment]
Same issue. On tablets the page leaves a white space on the right. It only occurs if you have more than one slide, so it is related to the animation.

**Comment by demon1br** [comment]
Same here, I'm pretty sure that is a animate.css problem.

**Comment by mmguide2003** [comment]
Hope this helps [http://stackoverflow.com/questions/31512366/slider-with-whitespace-appearing-on-right-of-smaller-screen]
