### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by robsonsobral** [animate-css/animate.css#874]
Hi! Have you ever considered BEM for naming the animations?

- http://getbem.com/
- https://en.bem.info/

It's an already widely used naming methodology.

**Comment by robsonsobral** [comment]
I was thinking something like:

- `bounce__in`
- `bounce__in--up`
- `bounce__in--down`
- `bounce__in--left`
- `bounce__in--right`
- `bounce__out`
- `bounce__out--up`
- `bounce__out--down`
- `bounce__out--left`
- `bounce__out--right`

But... You're the boss.

**Comment by eltonmesquita** [comment]
Makes sense but I still think it's unnecessary. Thanks for the idea! Feel free to suggest other improvements!
